### ISSUE TITLE
Noto Sans Arabic: Misplacement of tashkils after ligature LAM + ALEF WITH HAMZA

### ISSUE THREAD

**Issue by tianblr** [googlefonts/noto-fonts#1038]
I am not professional in typeface design nor in Arabic, so excuse me if I'm wrong. 

### Font 
Noto Sans Arabic

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-hinted.zip
Date: 2017-12-31

### Font Version
2.000;GOOG;noto-source:20170915:90ef993387c0; ttfautohint (v1.7)

### OS name and version
Windows 10, 1709

### Application name and version
Microsoft Word, as well as Photoshop CC 2018

### Issue
If I insert tashkils, such as FATHA (U+064E) and KARSA (U+0650), after the ligature LAM (U+0644) + ALEF WITH HAMZA (U+0623/U+0625), the tashkils are placed crossing the hamza rather than above/below it. However, the tashkils works well after standalone ALEF WITH HAMZA. 

This problem is not found in Noto Naskh though. 

### Character data
لأَ لإِ

U+0644 ARABIC LETTER LAM
U+0623 ARABIC LETTER ALEF WITH HAMZA ABOVE
U+0625 ARABIC LETTER ALEF WITH HAMZA BELOW
U+064E ARABIC FATHA
U+0650 ARABIC KARSA (but other tashkils should do as well)

### Screenshot
![image](https://user-images.githubusercontent.com/35773840/35344120-48b63182-0167-11e8-8629-95c14701f3be.png)

**Comment by kmuncie** [comment]
I would like to bump this because these character combinations are quite common in Arabic so the bugs really hinder the readability of Noto Sans Arabic. This issue, like most tagged `script-arabic`, is currently unassigned. Are any improvements for the Arabic fonts planned in the near-term? What help can be provided to help move these issues along?

## Where the font came from and when
https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf (June 2019)

## Font Version
Version 2.000; ttfautohint (v1.8.2)

## Numbered Examples Shown Below

### 1. لأَ

Char | Unicode | Description
-- | -- | --
ل | U+644 | ARABIC LETTER LAM
أ | U+623 | ARABIC LETTER ALEF WITH HAMZA ABOVE (ARABIC LETTER HAMZAH ON ALEF)
َ | U+64E | ARABIC FATHA (ARABIC FATHAH)

### 2. لأُ

Char | Unicode | Description
-- | -- | --
ل | U+644 | ARABIC LETTER LAM
أ | U+623 | ARABIC LETTER ALEF WITH HAMZA ABOVE (ARABIC LETTER HAMZAH ON ALEF)
ُ | U+64F | ARABIC DAMMA (ARABIC DAMMAH)

### 3. لإِ

Char | Unicode | Description
-- | -- | --
ل | U+644 | ARABIC LETTER LAM
إ | U+625 | ARABIC LETTER ALEF WITH HAMZA BELOW (ARABIC LETTER HAMZAH UNDER ALEF)
ِ | U+650 | ARABIC KASRA (ARABIC KASRAH)

### 4. لٱَ

Char | Unicode | Description
-- | -- | --
ل | U+644 | ARABIC LETTER LAM
ٱ | U+671 | ARABIC LETTER ALEF WASLA (ARABIC LETTER HAMZAT WASL ON ALEF)
َ | U+64E | ARABIC FATHA (ARABIC FATHAH)

### 5. لٱُ

Char | Unicode | Description
-- | -- | --
ل | U+644 | ARABIC LETTER LAM
ٱ | U+671 | ARABIC LETTER ALEF WASLA (ARABIC LETTER HAMZAT WASL ON ALEF)
ُ | U+64F | ARABIC DAMMA (ARABIC DAMMAH)

## Screenshot 

![arabic-issue-1](https://user-images.githubusercontent.com/582755/60992535-aee17880-a31a-11e9-9853-8e7c1fdcd280.jpg)

**Comment by kmuncie** [comment]
Has there been any movement on getting these issues resolved?

**Comment by nizarsq** [comment]
@kmuncie @tianblr [hinted](https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf) font updated couple days ago. Please check it out. This particular issue is a known issue as you can see reported in few bugs. I can see a partial fix but definitely there is an issue with placing diacritics correctly.
<img width="963" alt="Screen Shot 2020-06-02 at 8 59 31 PM" src="https://user-images.githubusercontent.com/22158882/83594698-bf8f7400-a514-11ea-832a-f22a0d2f341b.png">

**Comment by nizarsq** [comment]
This issue fixed in NotoSansArabic Version 2.004 fonts
