### ISSUE TITLE
Curly geresh and gershayim

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1130]
### Font
NotoSerifHebrew-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifHebrew-unhinted.zip
Date: 2018-03-04

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
U+05F3 and U+05F4 look like curly quotation marks. They should be straight.

### Character data
׳״
U+05F3 HEBREW PUNCTUATION GERESH
U+05F4 HEBREW PUNCTUATION GERSHAYIM

### Screenshot
![׳״](https://user-images.githubusercontent.com/1124347/38369864-b7ed9244-38b6-11e8-801f-019a5d9a28d8.png)

**Comment by dscorbett** [comment]
This bug is also present in Noto Rashi Hebrew.
![׳״](https://user-images.githubusercontent.com/1124347/71424947-6f5ade80-2665-11ea-8879-cfd2dd837ea7.png)

**Comment by marekjez86** [comment]
A quote from an Israeli font designer who responded to my question about this issue:
"Hi Marek,

This is actually the right shape for Geresh and Gershayim. The users that think this shapes should be straight are victims :) of Microsoft Word with the use of apostrophe (u+0022) and quotation marks (u+0027) these “curly quotation marks” are proper typographers quotation marks

Happy new year!
—yanek
--
yanek iontef
+972 (3) 560 5801
www.fontef.com
www.fontef.com/photolog"

**Comment by dscorbett** [comment]
> these “curly quotation marks” are proper typographers quotation marks

True, but this issue is not about quotation marks. I don’t mean geresh and gershayim should look like vertical ASCII quotes, but like the traditional diagonal geresh and gershayim, which look similar to some styles of typographical quotation mark. For example, here are some gershayim from the bottom of [the title page of a book published long before Microsoft Word](https://archive.org/details/amishahumshetora01marg/page/n8):
<img width="295" alt="Traditional gershayim" src="https://user-images.githubusercontent.com/1124347/71523630-de1f7e00-2897-11ea-90c1-9574fce5681d.png">
From a headline in the lower middle of [a page in a 1975 newspaper](https://archive.org/details/YediotAharonot1975IsraelHebrew/page/n1):
<img width="106" alt="Traditional gershayim" src="https://user-images.githubusercontent.com/1124347/71523924-2b501f80-2899-11ea-953b-560693f349cf.png">

**Comment by marekjez86** [comment]
BTW, the response was to this question:
"[...] claim is that in Noto Serif
U+05F3 HEBREW PUNCTUATION GERESH
U+05F4 HEBREW PUNCTUATION GERSHAYIM
"look like curly quotation marks. They should be straight."

38369864-b7ed9244-38b6-11e8-801f-019a5d9a28d8.png

I have similar shape for Noto Rashi Hebrew (reaching out to the older, I think Ladino, tradition).
Do you agree with this assertion?
Thanks for any opinion you might have."

**Comment by marekjez86** [comment]
Yet another response (highlight mine):
"Geresh & Gershayim are indeed separate marks than quote marks that historically were shaped as slanted lines, while quote marks were curly. **In practice, the only “quote-like” marks available on Hebrew keyboards are Geresh & Gershayim, which makes them double as quotation marks when typing Hebrew text.** As an aside, it should also be noted there aren’t any distinct Hebrew quotation marks in the Unicode standard. Due to these reasons, Hebrew readers make no distinction between the different marks, which is why I think both forms - straight and curly - are acceptable, and should be shaped in accordance to what better suits the font stylistically."

BTW, both responses came from the font developers that were not involved with Noto (I wanted to avoid the font developer(s) bias :-)).

**Comment by nizarsq** [comment]
@marekjez86 what is the final decision on this issue? is it WAI? below is the current rendering
<img width="847" alt="Screen Shot 2020-08-04 at 3 25 56 PM" src="https://user-images.githubusercontent.com/22158882/89351411-cc405d80-d666-11ea-836f-7d24fab1ecd7.png">
