### ISSUE TITLE
Noto Sans appears too big in GTK applications under Linux

### ISSUE THREAD

**Issue by ariasuni** [googlefonts/noto-fonts#1139]
### Font 
At least `NotoSans-Regular.ttf`.

### Where the font came from, and when
Arch Linux distribution
Date: 2018-04-05

### Font Version
131072

### OS name and version
Arch Linux (current)

### Application name and version

- Firefox 60.0b10
- Thunderbird 52.7.0

### Issue

EDIT: It’s not the font is different, but that it appears too big compared to Qt applications for example.

---

If I set Noto Sans as the default system font, Firefox and Thunderbird don’t use it.

What I did:

- Set Noto Sans as default font in System Settings (KDE)
- Set Noto Sans as default for GTK apps (`~/.config/gtk-3.0/settings.ini` has a line `gtk-font-name=Noto Sans Regular 10`)
- Set Noto sans as default font in fontconfig:
```xml
 <alias>
  <family>sans-serif</family>
  <prefer>
   <family>Noto Sans</family>
  </prefer>
 </alias>
```

Then, If I launch Firefox or Thundebird, they still don’t use Noto Sans for their interface.

**Comment by nRoof** [comment]
What font do they use instead on Arch? Are you sure this is not due to recent update of gtk3 or anything related to GNOME 3?

On Parabola GNU/Linux-libre, similar issue can be seen in all GTK+ apps from installed ones (gnome-system-monitor, GIMP, meld, virt-manager etc.). This distro is based on Arch, many packages are taken directly from their repo, including noto-fonts.

GTK+ apps still seem to use Noto Sans, but all the glyphs appear a bit larger then before the update (Noto Sans is set to size 10 in KDE Plasma System Settings).

Probably this is something related to how FreeType now handles them together with GTK+, because when fontconfig 'hintstyle' is set to 'slight', everything looks much closer to how it was before, then with 'medium'.

**Comment by ariasuni** [comment]
This does not seem to be related to an upgrade of GTK, since reverting `noto-fonts` to `20171025-2` (font version: `69468`) fix the problem.

However, I confirm this happens also in other GTK apps so that’s probably GTK-related (my `hintstyle` is `hintfull`).

See screenshots, before and after upgrade (as you mentioned, it does seems to be the same font, if that’s the case it’s larger and does not respect my font settings):

![screenshot_20180412_132733](https://user-images.githubusercontent.com/2446451/38674729-be6a106c-3e55-11e8-8b01-d29617ae086a.png) ![screenshot_20180412_132640](https://user-images.githubusercontent.com/2446451/38674733-c283dd5e-3e55-11e8-9e0c-d9109ab6655b.png)

**Comment by nRoof** [comment]
Yep, exactly the same can be seen under Parabola.

Did you try recent update of `cairo` from 2018-04-12 09:28 UTC ? It's not yet in Parabola repos, so I cannot test. If that doesn't help, I suggest asking about the problem in Arch forums. 

Also, FreeType doesn't render that ampersand well now at that size, and it didn't do that with `hintslight` earlier. Not sure if it's a font problem or FreeType's.

BTW, apparently, there's next to no visual difference here between `hintmedium` and `hintfull`. I remember noticeable difference between them in Infinality and FreeType < 2.7 times.

**Comment by nRoof** [comment]
I don't think exactly that, I meant that the problem might be anywhere, being it font itself, or rendering software, or even combination of issues in all of them. 

For example, look at [source of freetype2 Arch package](https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/freetype2): it has some custom patches, which may affect rendering. AFAIK, subpixel rendering, which may improve visual quality, is not enabled in their package (only subpixel hinting is enabled). All that may or may not contribute to how some particular font or even glyph is rendered.

There's nothing wrong about asking about this on Arch forums additionally, because there are a lot of people, and some of them may know the subject better than you or me, identify the issue or even provide a solution.

**Comment by pbui** [comment]
I am using Void Linux and experience the same thing.  The latest Noto Sans fonts (b207fc31b093948dfc6d77b47042ce2f335bc631) are larger than their previous version and don't look as good.

**Comment by 1202software** [comment]
Same issue, I opened a ticket elsewhere: https://unix.stackexchange.com/questions/445275/kde-plasma-gtk-fonts-too-large-after-update

It is indeed GTK-specific. Also, the font is the same. When I set `GDK_DPI_SCALE=0.98` it renders pretty much appropriately, however, icons are blurry and not all text elements render accordingly (some remain at DPI-scale 1). But it does show GTK applications seem to be rendering it a tad too large.

**Comment by GUiHKX** [comment]
Thanks a lot @ariasuni, I was experiencing the exact same issue and downgrading `noto-fonts` to version `20171025-2` in Arch Linux fixed it for me!

**Comment by 1202software** [comment]
There is a new version of the `noto-fonts` package (`noto-fonts-20181024-1`), this seems to do better. Though it's still not 100% you'd have to look hard to see the difference. I've posted an updated screenshot here: https://unix.stackexchange.com/questions/445275/kde-plasma-gtk-fonts-too-large-after-update

**Comment by guihkx** [comment]
Well, I'm on Arch Linux as well and I don't think it is fixed. Here's a comparison of Wireshark-GTK+ and Wireshark-QT, with `noto-fonts-20190111-1`:

![image](https://user-images.githubusercontent.com/626206/52388812-46465500-2a77-11e9-97f3-a9347dc419d8.png)


IMO the GTK+ one renders too big. Now here's another comparison using the same programs, but this time I've downgraded `noto-fonts` to `20171025-2`:

![image](https://user-images.githubusercontent.com/626206/52388855-873e6980-2a77-11e9-94eb-68f51baa0a10.png)

Now they look pretty much the same.

**Comment by ariasuni** [comment]
My problem reappeared for some reason… :/

**Comment by ariasuni** [comment]
I found a hackish solution on the [KDE Forum](https://forum.kde.org/viewtopic.php?f=309&t=154077#p405735).

The solution is to edit `~/.gtkrc-2.0` and `~/.config/gtk-3.0/settings.ini` and change the size of the font size to a non-integer value (graphical).

I personally use 10pt in Plasma/KDE, and 9.75 in GTK config, and now they display exactly the same size on screen.

**Comment by nizarsq** [comment]
@ariasuni can you check if the issue still reproducible using the current NotoSans version https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans

**Comment by xiaoLogin** [comment]
> I found a hackish solution on the [KDE Forum](https://forum.kde.org/viewtopic.php?f=309&t=154077#p405735).
> 
> The solution is to edit `~/.gtkrc-2.0` and `~/.config/gtk-3.0/settings.ini` and change the size of the font size to a non-integer value (graphical).
> 
> I personally use 10pt in Plasma/KDE, and 9.75 in GTK config, and now they display exactly the same size on screen.
> 
> Edit: I had to remove the package called `kde-gtk-config` on Arch Linux because it kept resetting the GTK font size to the one set for Plasma/KDE.

I have the same problem. This is so annoying

**Comment by ariasuni** [comment]
I’m not sure when, but this seems to have been fixed. I don’t have the issue anymore, and [this comment](https://bugs.kde.org/show_bug.cgi?id=421393#c12) says «that DPI scaling was incorrectly applied to GTK application».

I can confirm that font size is set to 10pt on both Plasma and GTK and that it appears the same size, and so that it’s a problem of Noto.
