### ISSUE TITLE
Spacing i’jam and tashkil are combining in Noto Sans Arabic

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1189]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansArabic-unhinted.zip
Date: 2018-02-04

### Font version
Noto Sans Arabic: Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Some spacing i’jam and tashkil have been given combining glyphs.

### Character data
ا﮲ا ا﮳ا ا﮴ا ا﮵ا ا﮶ا ا﮷ا ا﮸ا ا﮹ا ا﮺ا ا﮻ا ا﮼ا ا﮽ا ا﮾ا ا﮿ا ا﯀ا ا﯁ا اﱞا اﱟا اﱠا اﱡا اﱢا اﱣا اﹰا اﹲا اﹴا اﹶا اﹸا اﹼا اﹾا
U+FBB2 ARABIC SYMBOL DOT ABOVE
U+FBB3 ARABIC SYMBOL DOT BELOW
U+FBB4 ARABIC SYMBOL TWO DOTS ABOVE
U+FBB5 ARABIC SYMBOL TWO DOTS BELOW
U+FBB6 ARABIC SYMBOL THREE DOTS ABOVE
U+FBB7 ARABIC SYMBOL THREE DOTS BELOW
U+FBB8 ARABIC SYMBOL THREE DOTS POINTING DOWNWARDS ABOVE
U+FBB9 ARABIC SYMBOL THREE DOTS POINTING DOWNWARDS BELOW
U+FBBA ARABIC SYMBOL FOUR DOTS ABOVE
U+FBBB ARABIC SYMBOL FOUR DOTS BELOW
U+FBBC ARABIC SYMBOL DOUBLE VERTICAL BAR BELOW
U+FBBD ARABIC SYMBOL TWO DOTS VERTICALLY ABOVE
U+FBBE ARABIC SYMBOL TWO DOTS VERTICALLY BELOW
U+FBBF ARABIC SYMBOL RING
U+FBC0 ARABIC SYMBOL SMALL TAH ABOVE
U+FBC1 ARABIC SYMBOL SMALL TAH BELOW
U+FC5E ARABIC LIGATURE SHADDA WITH DAMMATAN ISOLATED FORM
U+FC5F ARABIC LIGATURE SHADDA WITH KASRATAN ISOLATED FORM
U+FC60 ARABIC LIGATURE SHADDA WITH FATHA ISOLATED FORM
U+FC61 ARABIC LIGATURE SHADDA WITH DAMMA ISOLATED FORM
U+FC62 ARABIC LIGATURE SHADDA WITH KASRA ISOLATED FORM
U+FC63 ARABIC LIGATURE SHADDA WITH SUPERSCRIPT ALEF ISOLATED FORM
U+FE70 ARABIC FATHATAN ISOLATED FORM
U+FE72 ARABIC DAMMATAN ISOLATED FORM
U+FE74 ARABIC KASRATAN ISOLATED FORM
U+FE76 ARABIC FATHA ISOLATED FORM
U+FE78 ARABIC DAMMA ISOLATED FORM
U+FE7C ARABIC SHADDA ISOLATED FORM
U+FE7E ARABIC SUKUN ISOLATED FORM

### Screenshot
Each character appears between two alefs to demonstrate the problem.
![ا﮲ا ا﮳ا ا﮴ا ا﮵ا ا﮶ا ا﮷ا ا﮸ا ا﮹ا ا﮺ا ا﮻ا ا﮼ا ا﮽ا ا﮾ا ا﮿ا ا﯀ا ا﯁ا اﱞا اﱟا اﱠا اﱡا اﱢا اﱣا اﹰا اﹲا اﹴا اﹶا اﹸا اﹼا اﹾا](https://user-images.githubusercontent.com/1124347/40280733-e685452e-5c25-11e8-8bef-e28a9aba004b.png)

**Comment by nizarsq** [comment]
Could you provide screenshot where i’jam and tashkil are combining occur? annotation much appreciated

**Comment by dscorbett** [comment]
I don’t understand: doesn’t the screenshot above already show that?

**Comment by nizarsq** [comment]
Sorry just saw the screenshot. For some reason didn't see it earlier.

**Comment by anthrotype** [comment]
so if I understand, the problem here is that those are classified by Unicode as spacing diacritics (with a non-zero advance), but in Noto Sans Arabic they are been treated as non-spacing combining diacritics and as such included in the GPOS mark feature.

The problem is that, in the ufo2ft library used by fontmake, among other things, to auto-generate the mark feature from the UFO glyphs' anchors, we use this simple rule to determine whether a glyph is to be considered a non-spacing mark: we check for the presence of underscore-prefixed anchor, e.g. "_top", and if there are any corresponding anchors named "top" in other base glyphs, then we automatically consider that glyph a combining mark in the mark feature. We don't take into account the Unicode properties of the glyphs involved. This works most of the time, since `_`-prefixed anchors are normally used inside non-spacing combining mark glyphs.
The problem is, sometimes, designers may place a `_`-prefixed anchors in a glyph because they want to use them to generate composite glyphs (e.g. precomposed accented glyphs) from base glyphs plus diacritics, but that glyph may be a spacing glyph (like is the case in the issue reported here).

This is the related issue: https://github.com/googlei18n/ufo2ft/issues/261

**Comment by nizarsq** [comment]
Apparently the issue reported in this bug is fixed. However, I see another issue unrelated to the issue reported. 
<img width="1258" alt="Screen Shot 2020-05-23 at 6 32 11 PM" src="https://user-images.githubusercontent.com/22158882/82743698-c7d0fd80-9d23-11ea-8c1a-6de97adb5a45.png">
