### ISSUE TITLE
Inconsistent serifs in Noto Sans Mono for i, j, l, and r

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1253]
### Font
NotoSansMono-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansMono-unhinted.zip
Date: 2018-06-18

### Font version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
Noto Sans Mono’s ⟨i⟩, ⟨j⟩, ⟨l⟩, and ⟨r⟩ differ from Noto Sans’s in that they have serifs. However, not all the characters based on those letters have serifs.

### Character data
iﬁﬃ jĳɟᶡ lȴɮʪʫ℔ⱡꞎﬂﬄ rɻʵ₢ꝵꭈꭊ
U+0069 LATIN SMALL LETTER I
U+FB01 LATIN SMALL LIGATURE FI
U+FB03 LATIN SMALL LIGATURE FFI
U+006A LATIN SMALL LETTER J
U+0133 LATIN SMALL LIGATURE IJ
U+025F LATIN SMALL LETTER DOTLESS J WITH STROKE
U+1DA1 MODIFIER LETTER SMALL DOTLESS J WITH STROKE
U+006C LATIN SMALL LETTER L
U+0234 LATIN SMALL LETTER L WITH CURL
U+026E LATIN SMALL LETTER LEZH
U+02AA LATIN SMALL LETTER LS DIGRAPH
U+02AB LATIN SMALL LETTER LZ DIGRAPH
U+2114 L B BAR SYMBOL
U+2C61 LATIN SMALL LETTER L WITH DOUBLE BAR
U+A78E LATIN SMALL LETTER L WITH RETROFLEX HOOK AND BELT
U+FB02 LATIN SMALL LIGATURE FL
U+FB04 LATIN SMALL LIGATURE FFL
U+0072 LATIN SMALL LETTER R
U+027B LATIN SMALL LETTER TURNED R WITH HOOK
U+02B5 MODIFIER LETTER SMALL TURNED R WITH HOOK
U+20A2 CRUZEIRO SIGN
U+A775 LATIN SMALL LETTER RUM
U+AB48 LATIN SMALL LETTER DOUBLE R
U+AB4A LATIN SMALL LETTER DOUBLE R WITH CROSSED-TAIL

### Screenshot
![iﬁﬃ jĳɟᶡ lȴɮʪʫ℔ⱡꞎﬂﬄ rɻʵ₢ꝵꭈꭊ](https://user-images.githubusercontent.com/1124347/42546306-db2bee20-848a-11e8-8806-befb332463c3.png)

**Comment by ariasuni** [comment]
Two other bug reports where opened about that: #1126 and #1136.

**Comment by nizarsq** [comment]
This issue still reproducible in the current font version https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono
<img width="602" alt="Screen Shot 2020-07-08 at 8 46 36 AM" src="https://user-images.githubusercontent.com/22158882/86940340-89d34180-c0f7-11ea-9474-e1efb76b597f.png">

**Comment by joshuakraemer** [comment]
In sans-serif monospace fonts, serifs are only added on letters that would otherwise be too narrow. Ligatures like fi and fl are already quite wide and thus do not need serifs. Adding serifs could actually make those ligatures look crowded and harder to read. Here are two other fonts for comparison, Monospace 821 and Segoe Mono:

![Monospace821](https://user-images.githubusercontent.com/10373011/88486608-26fafa80-cf7f-11ea-8692-fab1060945c2.png)
![SegoeMono](https://user-images.githubusercontent.com/10373011/88486610-29f5eb00-cf7f-11ea-9239-e56471fc9beb.png)

**Comment by marekjez86** [comment]
Design decision. Will not be changed.

**Comment by dscorbett** [comment]
What exactly is the design decision? It seems very odd that (for example) U+026C LATIN SMALL LETTER L WITH BELT and U+026D LATIN SMALL LETTER L WITH RETROFLEX HOOK should have serifs, but their combination, U+A78E LATIN SMALL LETTER L WITH RETROFLEX HOOK AND BELT, should not.
![ɬɭꞎ](https://user-images.githubusercontent.com/1124347/88487709-6f052780-cf55-11ea-9ee4-cb344a94b348.png)
@marekjez86, is this really intentional?

**Comment by marekjez86** [comment]
Correct, intentional although inconsistent. :-) To resolve some of the confusion renamed the font to be NotoMono (although we have already Sans fonts that look more "Serif-like" which we will keep as Sans; e.g., NotoSansBhaiksuki , NotoSansCherokee , ...).

**Comment by davelab6** [comment]
@dscorbett I agree that in your specific example, that 3rd glyph does look like it ought to have a serif and thus there is a valid design bug there. 

However, I agree with @joshuakraemer that the reason monospace 'sans' designs have serifs on some letters is because they are narrow, and the addition of serifs helps those letters fill the advanceWidth space mandated by the family, and present a more even paragraph texture or 'typographic color'; an `i` without serifs would appear to have a lot more white space on each side and create a 'swiss cheese' effect on paragraph texture. But then ligature characters that have to pack two letters into the same advanceWidth space (like `ĳ`) face the opposite problem, and the inclusion of the serifs may mean too much ink - and at small sizes, as Joshua says, harder to read.  

This is all separate to the naming concern :) 

I took a moment to mark which glyphs I think are fine (green), which probably ought to have serifs added (red), and a few situations I am less sure about, and would be happy to hear from the original designer about.

<img width="1020" alt="Screen Shot 2020-07-29 at 11 48 10 AM" src="https://user-images.githubusercontent.com/261579/88824176-ffc94680-d193-11ea-9bd6-b4272e640dc7.png">

![88487709-6f052780-cf55-11ea-9ee4-cb344a94b348](https://user-images.githubusercontent.com/261579/88824397-49199600-d194-11ea-921b-424fa9a842e3.png)

**Comment by davelab6** [comment]
@marekjez86 I propose let's chat with Monotype, as the original designers, about addressing this by (1) doing a comprehensive design review for this issue across the entire glyph set and (2) proposing a complete green/orange/red map of the glyph set, similar to what I sketched, and (3) shipping an update that fixes the issues where we agree there is a design improvement to be gained :)

**Comment by SteveMatteson** [comment]
These were intentional decisions meant to deliver the clearest representation of these forms in a wide range of monospace weights and widths. I considered the narrow and bolder styles of the design, the size this is intended to be used at (typically text) and the consistency to each other (the superscript vs regular shape of dotless jbar for instance). If the reviewers agree changing these for the entire weight and width range *improves* the legibility/recognition of these shapes then I'm happy to oblige. However the whole system needs to be considered - not just one weight at 144pt as shown above -steve
