### ISSUE TITLE
Clusters with nasalized consonants are not rendered properly in Grantha

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#1318]
### Title 
  > Clusters with nasalized consonants are not rendered properly in Grantha

### Font 
  > NotoSansGrantha-Regular.ttf

### Where the font came from, and when
  > Site: https://github.com/googlei18n/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansGrantha
Date: 2018-09-30

### Font Version
  >2.000
### Issue
  > Nasal vowel-less forms are encoded as consonant+ virama+candrabindu, however dotted circle is thrown, this seems like a rendering problem.
Also in the case of YA + VIRAMA+ CANDRABINDU+YA below-base form of YA is used, not the post-base form
The results should be as in https://www.unicode.org/L2/L2009/09372-grantha.pdf p. 41
### Character data
  > 1132F GRANTHA LETTER YA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎11301 GRANTHA SIGN CANDRABINDU
 ‎0020 SPACE
 ‎11332 GRANTHA LETTER LA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎11301 GRANTHA SIGN CANDRABINDU
 ‎0020 SPACE
 ‎11335 GRANTHA LETTER VA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎11301 GRANTHA SIGN CANDRABINDU
 ‎0020 SPACE
 ‎1132F GRANTHA LETTER YA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎11301 GRANTHA SIGN CANDRABINDU
 ‎1132F GRANTHA LETTER YA
 ‎0020 SPACE
 ‎11335 GRANTHA LETTER VA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎11301 GRANTHA SIGN CANDRABINDU
 ‎11335 GRANTHA LETTER VA
 ‎0020 SPACE
 ‎11332 GRANTHA LETTER LA
 ‎1134D GRANTHA SIGN VIRAMA
 ‎11301 GRANTHA SIGN CANDRABINDU
 ‎11332 GRANTHA LETTER LA
𑌯𑍍𑌁 𑌲𑍍𑌁 𑌵𑍍𑌁 𑌯𑍍𑌁𑌯 𑌵𑍍𑌁𑌵 𑌲𑍍𑌁𑌲

### Screenshot
  > output from hb-view
![granthatest](https://user-images.githubusercontent.com/23263723/46411209-c874e480-c738-11e8-9ba2-4edb2a045274.png)

**Comment by punchcutter** [comment]
This is the same issue as https://github.com/googlei18n/noto-fonts/issues/1319 which is a problem because of USE shaping cluster validation. 

Regarding the comment about p.41 of the Unicode proposal this works as expected if USE shaping is followed:
<img width="545" alt="grantha_unicode_proposal_p41" src="https://user-images.githubusercontent.com/11257204/46417795-473d3380-c6df-11e8-8dc6-bda655034e72.png">
U+11324,U+1133E,U+1131E,U+200D,U+1134D,U+1131B,U+0952,U+1132F,U+1134D,U+1132F,U+1134D,U+11335,U+11301,U+1CF4,U+11328,U+1134D,U+11317,U+0952

**Comment by simoncozens** [comment]
This is now fixed in Harfbuzz thanks to the above PR. Other shaping engines should hopefully follow.
