### ISSUE TITLE
Consonant with virama clashing with repha in Serif Kannada

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#1340]
### Font 
  > NotoSerifKannada-Regular.ttf
  
  > For example:
  >   Site: https://raw.githubusercontent.com/googlei18n/noto-fonts/master/phaseIII_only/hinted/ttf/NotoSerifKannada/NotoSerifKannada-Regular.ttf
  >   Date: 2018-10-14 

### Font Version
  >2.001
### Issue
  >consonant with virama, if there is an ottu form below clashes with the arkavottu( repha)
  
  2. Observed results
![image](https://user-images.githubusercontent.com/23263723/46917165-4c548980-cfe1-11e8-871d-6cbcbfa14aca.png)

  3. Expected results
![image](https://user-images.githubusercontent.com/23263723/46917172-59717880-cfe1-11e8-9aea-c8ae75b2af4c.png)
![image](https://user-images.githubusercontent.com/23263723/46917176-65f5d100-cfe1-11e8-8619-e223f124bca2.png)

 
### Character data
  > ವರ್ಲ್ಡ್ ಬರ್ಸ್ಟ್ ಮಾರ್ಕ್ಸ್ etc.

**Comment by JelleBosmaMT** [comment]
I downloaded Noto Serif Kannada 2.001 ttfautohint v1.8.2 modification date 26 September 2019 and cannot reproduce the issue in Windows 10 nor in Mac OS.
![knda autohint](https://user-images.githubusercontent.com/12729011/66466361-d9aaac80-ea82-11e9-8b1e-1b9d06fe4f27.PNG)

The issue is most likely caused by an older version of the font make software not correctly interpreting the source file. _(The Windows screenshot shows auto hinting defects, but that is issue of another project.)_

**Comment by sridatta1** [comment]
Closing this issue, as reported by @JelleBosmaMT above, I don't see the issue in the Noto Serif Kannada font 2.001  ttfautohint (v1.8.2) downloaded from https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/hinted/ttf/NotoSerifKannada/NotoSerifKannada-Regular.ttf
![image](https://user-images.githubusercontent.com/23263723/82141670-129ad300-9855-11ea-9441-a6742a2b63ef.png)
