### ISSUE TITLE
anudatta colliding with ra-ottu occuring as third consonant of the cluster in Noto Sans Kannada

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#1341]
### Font 
  NotoSansKannada-Regular.ttf

### Where the font came from, and when
  > For example:
  >   Site: https://raw.githubusercontent.com/googlei18n/noto-fonts/master/phaseIII_only/hinted/ttf/NotoSansKannada/NotoSansKannada-Regular.ttf
  >   Date: 2018-10-14

### Font Version
  > 1.04

### Issue
  > In a syllable with three consonants like ṣṭra, ndra etc. the anudatta collides with the ra-ottu, thus the vedic sign isn't distinct and looks the ra-ottu is extended below, the vedic sign anudatta can be placed little left so that it is visibly distinct.

  2. Observed results
![image](https://user-images.githubusercontent.com/23263723/46917784-63e34080-cfe8-11e8-8496-9bbfa252bf8f.png)

 
### Character data
  ಇನ್ದ್ರಂ॒ ಇನ್ದ್ರ॒ ರಾಷ್ಟ್ರೇ॒ಽಸ್ಮಿ

**Comment by nizarsq** [comment]
Look like this issue is fixed, please reopen if you have other thoughts. I used the font in this [directory](https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/ttf/NotoSansKannada/NotoSansKannada-Regular.ttf). Attached a screenshot of the current render. 
<img width="1367" alt="Screen Shot 2020-06-16 at 10 09 27 PM" src="https://user-images.githubusercontent.com/22158882/84857664-66e4ce80-b01e-11ea-9a4c-a3b01b1a58aa.png">
