### ISSUE TITLE
Problems with the Greek letters in Noto Sans Elbasan

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1363]
### Font
NotoSansElbasan-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/d7af81e614086435102cca95961b141b3530a027/hinted/NotoSansElbasan-Regular.ttf
Date: 2018-10-29

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770;ttfautohint (v1.8.2)

### Issue
The Greek letters in Noto Sans Elbasan do not match the Elbasan letters: they are caps-height instead of x-height, use only one width for all strokes, and have angular ends instead of round. No such stylistic distinctions between the two scripts are attested in the [Elbasan Gospel Manuscript](https://web.archive.org/web/20151011181125/http://www.albanianliterature.net:80/authors/authors_early/gregory_of_durres/gregory_EGM1.html).

The font supports more Greek letters than are attested in the manuscript (i.e. just ⟨Β⟩, ⟨Ι⟩, and ⟨Λ⟩) presumably to complete the set of Greek numerals, but the sampi for 900 is missing.

### Character data
𐔐ΛϠ
U+10510 ELBASAN LETTER LE
U+039B GREEK CAPITAL LETTER LAMDA
U+03E0 GREEK LETTER SAMPI

### Screenshot
![𐔐ΛϠ](https://user-images.githubusercontent.com/1124347/47741536-e870c880-dc50-11e8-9ddd-d4e456cb845e.png)

**Comment by simoncozens** [comment]
I'm not sure I'm too bothered about the stylistic difference here - we're making a font for a *script*, not specifically for a manuscript, and fonts make their own decisions about x-height, cap-heights, stroke endings, etc. If we decide to make a distinction between Elbasan letters and Greek letters, I think that's a legitimate decision. (Yes, of course this is motivated reasoning and I'm only saying it because it's much easier to continue stealing glyphs from Noto Sans than to commission the drawing of new ones. But I still don't think it's an *intrinsically* wrong approach; it's OK for a mixed-script document to not harmonise graphically between the scripts.)

I'll steal the sampi, though, for completeness.

**Comment by dscorbett** [comment]
A Japanese font would not mix kaisho Katakana with Gothic Hiragana. A UPA font would not mix geometric sans-serif Latin with high-contrast serifed Cyrillic. This is a font for one writing system, not a set of disparate scripts merged for convenience into one font. Maybe it is not _wrong_ for the Elbasan and Greek glyphs to be unharmonized, but it is kind of sloppy.
