### ISSUE TITLE
Contextually inappropriate half forms in Newa

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1377]
### Font
NotoSansNewa-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/64f57055a31ee72789437d786e969ded9a1231f9/hinted/NotoSansNewa-Regular.ttf
Date: 2018-11-07

### Font version
Version 2.000;GOOG;noto-source:20181019:f8f3770

### Issue
<i>Ta</i> and <i>ra</i> have half forms even at the ends of clusters, where they should not have half forms.

### Character data
𑐟𑑂 𑐬𑑂
U+1141F NEWA LETTER TA
U+11442 NEWA SIGN VIRAMA
U+0020 SPACE
U+1142C NEWA LETTER RA
U+11442 NEWA SIGN VIRAMA

### Screenshot
![𑐟𑑂 𑐬𑑂](https://user-images.githubusercontent.com/1124347/48366000-8bc2d400-e67a-11e8-8b3b-cfe905ae4f1b.png)

**Comment by marekjez86** [comment]
using updated Newa from https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/unhinted/otf/NotoSansNewa I get

<img width="163" alt="Screen Shot 2019-05-16 at 10 05 26" src="https://user-images.githubusercontent.com/13322623/57873433-15d32d00-77c3-11e9-85d6-566063fc807f.png">

appears to be fixed

**Comment by punchcutter** [comment]
Also note this behavior was changed so that the Ra half form (eyelash repha) is now formed with <RA, VIRAMA, ZWJ>. See https://www.unicode.org/L2/L2019/19170-newa-change.pdf  
Also, it was decided with Nepal Lipi Guthi that the special initial form of Ta is now formed with <TA, VIRAMA, ZWJ>, but unlike what's stated in the Unicode proposal this form doesn't only occur before Ka and Sa. It is also seen before other letters in old manuscripts, but not used in modern Newa. So the default for initial Ta is the initial condensed form. If the special form is desired it can be achieved with ZWJ.
