### ISSUE TITLE
.notdef in 'blws' in Noto Serif Gurmukhi

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1454]
### Font
NotoSerifGurmukhi-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlei18n/noto-fonts/blob/0a522f55b37b72f8b5013bd76fefddc74c9aeb4b/phaseIII_only/unhinted/otf/NotoSerifGurmukhi/NotoSerifGurmukhi-Regular.otf
Date: 2019-02-21

### Font version
Version 2.000

### Issue
Some of the 'blws' lookups in Noto Serif Gurmukhi include .notdef in their coverage tables. Did the font get corrupted?

**Comment by JelleBosmaMT** [comment]
There are substitution rules in the source file using .notdef. So it is intentional and not a corruption. I do not understand what the intention of the designer was. But the rules with .notdef are "ignore substitution" rules, without any other substitution in the lookup. So they do not do anything at all.
