### ISSUE TITLE
Noto Sans Arabic has no english characters

### ISSUE THREAD

**Issue by Ronser** [googlefonts/noto-fonts#1481]
### Title 
The Noto Sans Arabic font does not have any English characters. I am building an Arabic document with occasional English words. This font is useless as it doesn't contain English characters.

### Font 
Noto Sans Arabic font family

### Where the font came from, and when
https://www.google.com/get/noto/

### Font Version
2.000 Properties.

### OS name and version
Windows 7

### Application name and version
Adobe Acrobat PDFs

### Issue
  No English characters in the Noto Sans Arabic font family mean it's useless when creating a PDF and selecting font for content that features Arabic and English.

**Comment by marekjez86** [comment]
@Ronser : thank you for the feedback.
This is by design :-(

We also do not have a good answer for people who build "an Arabic document with occasional Chinese words", "a Chinese document with occasional Arabic words", "a Javanese document with occasional Chinese words", etc...
However, we are making a note of the request...

**Comment by Ronser** [comment]
I appreciate it is impossible to support combinations. But English A-Z
should be an exception as it is often used as a global language. It is
already incorporated in the Noto CJK font family, which I understand has a
fairly full character set. Why not the others?

**Comment by marekjez86** [comment]
For Noto CJK we had no option but to accept the existing Latin glyphs (and it is NOT any of Noto Latin Greek Cyryllic fonts) based on the contract/deal we signed. As I  mentioned, we are trying to figure out how to change our current policy.

**Comment by jungshik** [comment]
If one needs a version of Noto Sans with Arabic plus basic Latin, one can
 easily make one by merging basic Latin for om Noto sans lgc to Noto sans Arabic.

**Comment by Chrisp90** [comment]
Hello there,

Is this issue still on someone's radar? I work in a Translation/Localization company and we translate documents for international clients. One of our clients decide to use the Noto Font for their multilingual documents so that we don't need to use different font per langauge. Arabic is among those languages and a lot of word with Latin Characters are used as well. It would make our lives easier if the font could support both scripts so that we don't have to apply a font for the Arabic script and another one for the Latin script.

I think it's awesome that a font (family) covers so many languages, it helps people like me (Desktop Publisher) a lot!!! Thank you for this!

Thank you in advance for your time.

Best,
Chris
