### ISSUE TITLE
Update Noto Sans Adlam

### ISSUE THREAD

**Issue by sven-oly** [googlefonts/noto-fonts#1502]
## Defect Report
Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title 
Noto Sans Adlam needs refresh

### Font 
 NotoSansAdlam*.ttf.

### OS name and version
All

### Application name and version
  > If the issue is observed using a specific app.

### Issue
The representative font for Adlam script in the Unicode standard will be updated soon. Noto Sans Adlam's style should be updated to be more in line with the original intent of the script, which is much better represented by the new font Ebrima/Kigelia (coming in Windows 10), which will soon be part of the Unicode Standard's page.

  1. Steps to reproduce
  2. Observed results
     Current Noto Sans Adlam's style is not consistent with the original intent of the script's developers.
  3. Expected results
  4. Additional information 
Here's the proposal for updating the font in the standard:
https://www.unicode.org/L2/L2019/19119-adlam-font-repl.pdf

Here is the current Unicode page for Adlam: http://www.unicode.org/charts/PDF/U1E900.pdf

### Character data
  > Please include real character data to illustrate your issue-- Unicode codepoints are helpful.  This makes it possible for developers who don't know the language or script to copy/paste the text to reproduce the issue.

### Screenshot
  > If possible, include a screenshot or an image illustrating the issue.
  > Annotations are also helpful.

## Tools for reporting bugs
  Useful tools for reporting bugs are available at: https://github.com/googlei18n/
  
### Harfbuzz hb-view and hb-shape
  These are part of the HarfBuzz distribution and can help isolate if an issue is in the app/OS, shaping engine, or font.
  * hb-view renders the text with the exact font (for example, to see how ligatured characters shape) using your installed version of HarfBuzz.

For example:
```
  hb-view --font-file {path to font} --text-file {path to text file} --output-file '{sample}.png'
```

* hb-shape shows glyph selection and positioning

### Fontview
  * Fontview displays the text.

### Fontdiff
  * Fontdiff displays the text using two versions of the font side by side.

**Comment by marekjez86** [comment]
@sven-oly : Thank you for the reminder. 

Noto Adlam history:
===============
2016 June 21: Unicode® 9.0.0 was published. It had the first specification of Adlam
--- :  Design phase
2016 August 24: Design phase is completed
--- : Script implementation phase based on the design from 2016 August 24 was started from that date
2017 January 10: Noto Sans Adlam sources are published and font built
--- : Since that time, Barry brothers changed the following:
-  In Unicode® 9.0.0 Adlam version, the upper case letter was just a larger version of a lowercase letter.  Now it is very different (imagine that for upper case P you need to write now two vertical strokes instead of one - that's the change for most/all characters).
-  Barry brothers also changed significantly both upper case and lower case for these four characters: kaf, kha (supplementary), gbe (supplementary) and sha (supplementary)
-  Also these marks gained different shapes:
  - 1e95e initial exclamation mark
  - 1e95f initial question mark
IMHO, the first Unicode standard for Adlam was published prematurely. We will commission an update to Noto Sans Adlam when the new Unicode 13.0 standard is published (it's a Noto policy only publish Unicode PUBLISHED scripts). I expect Unicode 13.0 to be published in the first half of 2020. Please expect a new Noto adhering to it soon thereafter.

**Comment by simoncozens** [comment]
Noto Sans Adlam 3.0 now follows the proposed forms. For example:

```
 $ shape NotoSansAdlam-Regular.ttf -u 1e912,1e912,1e912
[u1E912.fina=2+833|u1E912.medi=1+833|u1E912.init=0+585]
```
![shape](https://user-images.githubusercontent.com/106728/151998905-4d8455c6-dc0b-4cd6-8b57-f6a93b473ac5.png)
<img width="322" alt="Screenshot 2022-02-01 at 15 34 33" src="https://user-images.githubusercontent.com/106728/151999038-3ca93258-0555-4853-8912-466bb1a12e17.png">
