### ISSUE TITLE
name ID 4 and name ID 6 have 'Regular' in all variation fonts 

### ISSUE THREAD

**Issue by jungshik** [googlefonts/noto-fonts#1517]
Name ID 4 (full name)  and ID 6 (postscript name)  have 'Regular' in variation fonts. Shouldn't it be dropped for VF ?   

For instance, Noto Sans Thai VF has 'Noto Sans Thai Regular' (id 4) and 'NotoSansThai-Regular' (id 6), but I think they'd better be 'Noto Sans Thai' and 'NotoSansThai'.   

https://docs.microsoft.com/en-us/typography/opentype/spec/name does not have much to say about this other than ID 25. Related issue is #869 .  If there were  ID 25 or ID 16,  we would not have to worry about ID 6 per [Adobe technical note 5902] (https://wwwimages2.adobe.com/content/dam/acom/en/devnet/font/pdfs/5902.AdobePSNameGeneration.pdf) , but we don't. 

Perhaps, this is a fonconfig issue. When constructing 'FullName' for named instances, fontconfig just uses name ID 4, but it'd better construct fullname by concatenating ID 1 and subfamilyID from fvar. 
I'll raise an issue in fontconfig.

**Comment by jungshik** [comment]
@anthrotype

**Comment by anthrotype** [comment]
This is expected because the default master font on top of which the VF is built correspond to the "Regular"  and fonttools currently doesn't change the default instance's names when building a VF.

I don't think we need the nameID=25 for the "Variations PostScript Name Prefix"; it's true that the algorithm from the linked "Adobe Technical Note 5902" says that, if the latter is missing, one should take the "typographic family name (nameID 16)" and remove non-ASCII characters. But the nameID=16 itself is optional and can be omitted when it is the same as nameID=1 (family name).
