### ISSUE TITLE
When using NotoSerifHebrew-Regular.ttf to write ! (exclamation mark) I get tofu

### ISSUE THREAD

**Issue by avitaleli** [googlefonts/noto-fonts#1565]
### Title 
  > When using NotoSerifHebrew-Regular.ttf to write ! (exclamation mark) I get tofu

### Font 
  > 'NotoSerifHebrew-Regular.ttf'.

### Where the font came from, and when
  >  https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifHebrew-hinted.zip

### Font Version
  > I use it when writing a canvas from a python script running on linux Properties.
  > * Linux -- use (Gnome) Font Viewer: open a font and click on Info tab.

### OS name and version
  > Ubuntu 18.04, running with a Python 3.6 scipt

### Issue
  > I am loading this font to be used in a canvas generating a PDF. I am writing an Hebrew sentence ending with !, however the sentence is correctly displayed, however the ! is displayed as tofu.

**Comment by jungshik** [comment]
The font does not cover the ascii. You need to use another font (e.g moto serif) along with moto serif Hebrew.

**Comment by elic9** [comment]
Thank you for your email, I think ot would be a problem to mix both fonts.
Is it possible to merge both files into one ttf?

**Comment by jungshik** [comment]
What do you mean by that it's a problem? You can use more than one fonts in your off generation code. It's a bit more work, but a lot of folks do that.

If you can't, you can merge noto serif's ascii range to noto serif Hebrew with tools like fonttools.

**Comment by elic9** [comment]
Hi,

I am using a python library that as much as I could see does not enable
adding 2 fonts, you have to choose one font when needed (I am still
checking this). However I will try to merge as you mentioned.

Thank you,
Eli

**Comment by verdy-p** [comment]
Noto is not designed to allow merging scripts. In fact it would be impossible to merge all possible pairs of scripts (ore more) in one font. Even a single script cannot be used from a single font: Ideographic covers now more than one plane and a third plane will soon be added with Unicode 13.0 (announced recently).

You should think about upgrading your tools to allow specifying list of font families instead of just one. alternatively, may be your OS or software provides a way to declare a "virtual" composite font (this is possible in CSS for example, to be used in HTML, SVG and so on).

There are packages in Python that allow doing that for various output formats, including for generating PDFs (Typically PDF generators are extracting the glyphs they need from various fonts and will build an internal embedded font). If your PDF generator cannot do that, think about using better generators.

I'm in favor of keeping scripts separate because it allows more freedom and better mechanisms for fallbacks and with corect metrics and designs suitable for each script. Latin metrics and Hebrew metrics are very different. And it's much simpelr to design coherent fonts for separate scripts, and then tune each of them for the best coverage (including diacritics, variants, ligatures, kerning and all the required OpenType features for required contextual forms...)

Hebrew has its own complexities that would also complicate the already complex Latin script. And including a partial coverage of Latin would be even worse.

But if one wants to have less fonts, ideally there should be at least 5 families:
 1. all simple alphabetic scripts, and common punctuations and symbols (without any emoji), except Hangul, but including the math symbols.
 2. all Semitic abjads
 3a. all Indic abugidas (possibly merged with the previous in a compound "Complex" family handling required Opentype features)
 3b. all syllabaries (possibly merged wit hthe previous in a compound "Complex" family handling required Opentype features)
 4. Sinograms (one family for each Hans, Hant, Kore, Jpan style, plus one for supplementary ideographs that don't need specialization); Hangul should be in the Kore-specialized font, Bopomofo should be in the Hans-specialized font, Japanese syllabaries should be in the Jpan-specialized font.
5. Emojis (due to their specific colorful behavior).

For now these 5 groups can fit in the limits of OpenType (65535 glyphs per font)

But Noto is an free open project, you can still derive these 5 families for the existing base Noto families.

**Comment by nizarsq** [comment]
@marekjez86 Is this WAI? I don't expect to see (exclamation mark) in NotoSerifHebrew  or NotoSansHebrew unless there is a decision to add the basic punctuation marks.

**Comment by kosmynkab** [comment]
I checked a few scripts and there are inconsistencies in terms of the punctuation added to the glyphset. Also numbers. If that is to be incorporated it's probably a good idea to have it done universally across scripts. Perhaps a replicated set of numbers, punctuation, and special characters?

**Comment by simoncozens** [comment]
Merging into #2257.
