### ISSUE TITLE
Santali Language but English font

### ISSUE THREAD

**Issue by GoogleCodeExporter** [googlefonts/noto-fonts#160]
```
What steps will reproduce the problem?
1. Santali Language has shown two fonts in the language search but appeared as 
English font.
2. Do not deface.Keep  it oroginal fonts.
3. Leg is mine but head is your what it means?

What is the expected output? What do you see instead?
Original face of the Santali Fonts.
What version of the product are you using? On what operating system?
Chrome OS.


Please provide any additional information below.
Kindly remove English font from Santali language search bar. 


```

Original issue reported on code.google.com by `kmurmu918@gmail.com` on 24 Sep 2014 at 3:11

**Comment by behdad** [comment]
cc @nyshadhr9 @roozbehp

**Comment by behdad** [comment]
cc @davelab6

**Comment by brawer** [comment]
Okay, so I grabbed a couple ChromeBooks and checked how Santali (in the “Ol Chiki” script) looks on ChromeOS. One test machine had the “stable” channel (version 41.0.2272.89, platform 6680.64.0), and two had the “beta” channel (version 44.0.2403.54, platform 7077.49.0) of ChromeOS. On all three ChromeBooks, the Ol Chiki glyphs were getting displayed correctly. ChromeOS used the “Noto Sans Ol Chiki” font that ships with ChromeOS.
https://en.wikipedia.org/wiki/Ol_Chiki_alphabet#Unicode_chart
https://en.wikipedia.org/wiki/Ol_Chiki_(Unicode_block)
http://www.google.com/get/noto/#sans-olck

So, there does not seem to be any rendering or font problem — if a web page contains Santali (Ol Chiki) text, today’s version of ChromeOS will display it perfectly fine. However, to be useful for people, users would also need some way for entering text in Santali. Here's a document that describes how text input works on ChromeOS:
https://www.chromium.org/chromium-os/chromiumos-design-docs/text-input#TOC-Basic-architecture
(ChromiumOS is the open-source foundation of ChromeOS)

According to that overview document, text input on ChromeOS is based on iBus:
https://github.com/ibus/ibus/wiki

Therefore, at least if I understand this correctly (others on this bug: please correct me if I'm wrong), the next step would be to implement a Santali input method in iBus. Because iBus is an open-source project, anyone can do this — you don't need to wait for Google. This work would be useful ChromeOS, but also for any other systems that use iBus.

**Comment by jungshik** [comment]
As @brawer wrote, Chrome OS 44 (which turned stable a few days ago) does have this script covered with Noto font.
