### ISSUE TITLE
Misplaced anchor below U+08AB ARABIC LETTER WAW WITH DOT WITHIN

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1610]
### Font
NotoSansArabic-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/9c74a9735acb66df9a41ad86e58020430ede9a9d/phaseIII_only/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
Date: 2019-11-05

### Font version
Version 2.000; ttfautohint (v1.8.2)

### Issue
The anchor point below U+08AB ARABIC LETTER WAW WITH DOT WITHIN is too high.

### Character data
ࢫࣦ
U+08AB ARABIC LETTER WAW WITH DOT WITHIN
U+08E6 ARABIC CURLY KASRA

### Screenshot
![ࢫࣦ](https://user-images.githubusercontent.com/1124347/68214082-c8ce5780-ffaa-11e9-96e1-86caf484d49a.png)

**Comment by nizarsq** [comment]
This issue fixed in version 2.5. Please try the new version from https://github.com/googlefonts/noto-fonts/blob/master/phaseIII_only/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf
<img width="494" alt="Screen Shot 2020-05-19 at 10 59 32 PM" src="https://user-images.githubusercontent.com/22158882/82410381-9c4ccb00-9a24-11ea-9a13-515944a4019f.png">

**Comment by nizarsq** [comment]
This issue reproducible  on v1.8.2
<img width="612" alt="Screen Shot 2020-05-20 at 3 38 58 PM" src="https://user-images.githubusercontent.com/22158882/82504405-2b52f500-9ab0-11ea-9ac7-d5c1c171871d.png">
