### ISSUE TITLE
U+1C29 LEPCHA VOWEL SIGN OO is too wide in klyō

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#1734]
### Font
NotoSansLepcha-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/fcf8d5d5568fc96efcc4cbe6f9fbd402f62de98a/phaseIII_only/unhinted/otf/NotoSansLepcha/NotoSansLepcha-Regular.otf
Date: 2020-05-05

### Font version
Version 2.000

### Issue
The width of vowel sign <i>ō</i> in this font depends on the width of the base letter. Some base letters ligate with medial <i>ya</i> or <i>ra</i>, but that has no effect on the <i>ō</i>; for example, it is narrow above both <i>nga</i> and <i>ngya</i>. The only exception is that the vowel sign is narrow above <i>kla</i> but default-width above <i>klya</i>.

### Character data
ᰁᰩᰁᰤᰩ
U+1C01 LEPCHA LETTER KLA
U+1C29 LEPCHA VOWEL SIGN OO
U+1C01 LEPCHA LETTER KLA
U+1C24 LEPCHA SUBJOINED LETTER YA
U+1C29 LEPCHA VOWEL SIGN OO
ᰅᰩᰅᰤᰩ
U+1C05 LEPCHA LETTER NGA
U+1C29 LEPCHA VOWEL SIGN OO
U+1C05 LEPCHA LETTER NGA
U+1C24 LEPCHA SUBJOINED LETTER YA
U+1C29 LEPCHA VOWEL SIGN OO

### Screenshot
![ᰁᰩᰁᰤᰩ ᰅᰩᰅᰤᰩ](https://user-images.githubusercontent.com/1124347/81129254-c759f980-8f11-11ea-9ba5-02ab27c2d911.png)

**Comment by nizarsq** [comment]
@dscorbett Am having some difficulty in understanding this issue. In the issue title and in characters data you are using U+1C29,  but in the issue description you are using U+014D. is that  some kind of typo error or I'm missing something here?

**Comment by dscorbett** [comment]
This issue is about U+1C29 LEPCHA VOWEL SIGN OO. I used the Latin U+014D in the issue description to represent the Lepcha U+1C29. Similarly, I used the Latin <U+006B, U+006C> to represent the Lepcha U+1C01, and the Latin U+0079 to represent the Lepcha U+1C24. This technique is called [transliteration](https://en.wikipedia.org/wiki/Transliteration).

**Comment by simoncozens** [comment]
Is the problem here that it is too wide in kylō or actually that it is too narrow in ngyō? To put it another way, should the OO vowel cover the whole cluster, or should it be fixed width?

In Michael Everson's proposal, Figure 7 seems relevant. It gives the manuscript example:

<img width="128" alt="Screenshot 2022-04-23 at 23 21 06" src="https://user-images.githubusercontent.com/106728/164947880-538b456d-ce7f-44b7-accd-8255770764c1.png">

which certainly seems to cover the whole cluster; followed by the "tentative rendering into modern script":

![lepcha](https://user-images.githubusercontent.com/106728/164947924-b5d88e15-fb1e-4cf4-809e-6c39200c18e6.jpg)

Is this just a stylistic issue? I think we need to hear from script users.

**Comment by simoncozens** [comment]
Actually, I've seen enough - the SIBLAC fonts and SIL Mingzat behave as you have described.
