### ISSUE TITLE
Noto Sans TC introduces extra spacing when ' is used

### ISSUE THREAD

**Issue by georgioajency** [googlefonts/noto-fonts#1756]
## Defect Report

Use this template for filing a defect report. For feature requests and other matters, you can use part of the template and delete what you don't need.

### Title

> Noto Sans TC introduces extra spacing when ' is used

### Font

> Full file name, for example 'NotoSans TC'.  
> You can upload the problem font here unless it is a Chinese, Japanese or Korean font (these are large).

### Where the font came from, and when

> Site: https://fonts.google.com/specimen/Noto+Sans+TC?preview.text=We%27ll&preview.text_type=custom&query=noto+sans+tc  
> Date: 2020-05-25

### Font Version

> *   1.004

### OS name and version

> Windows

### Application name and version

> Adobe XD and Figma

### Issue

> Summarize the issue briefly -- one paragraph preferred

1.  Download fonts
2.  Install all fonts
3.  Open Figma or XD
4.  Select font
5.  Type any text which has ' in it ex. We'll

### Screenshot

> ![](https://user-images.githubusercontent.com/43877959/82860396-0a1e5880-9f37-11ea-88c2-c466c7d50e46.png)

## Tools for reporting bugs

Useful tools for reporting bugs are available at: https://github.com/googlei18n/

**Comment by punchcutter** [comment]
Sorry this isn't so clear. The space is intentional as certain glyphs are meant for Chinese setting. The TC, SC, and HK fonts for Source Han Sans/Noto Sans CJK show this behavior as explained on p.11 of https://github.com/adobe-fonts/source-han-sans/blob/release/SourceHanSansReadMe.pdf 
That might not be clear either since there doesn't seem to be any link on https://github.com/googlefonts/noto-cjk, but that's a place to look for more detailed information.

**Comment by georgioajency** [comment]
Oh. Thanks for the clarification. Makes sense.

I thought it was an issue as when I tried typing out the same within the Google Font page it worked fine. 

![](https://user-images.githubusercontent.com/43877959/82980434-1bcf3100-a007-11ea-8eca-5156a35a9d4d.png)

**Comment by nizarsq** [comment]
Since this behavior is intentional, I'm going to close this bug.
