### ISSUE TITLE
New linespace and mark problems in Noto Sans Arabic 2.5

### ISSUE THREAD

**Issue by Chen-TX** [googlefonts/noto-fonts#1774]
### Font:
Noto Sans Arabic font family

### Where the font came from:
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansArabic

### Font Version:
2.5

### Issue
1. When displaying letters that have low bottom matrices (e.g. ج, ع, ي), the lowest parts of the characters are "cut off".
2. Problems with Shadda marks - the marks' positions are so low that they interfere with the letters (e.g. اللُّغة).
3. It seems that Noto Sans Arabic 2.5 adopts totally new designs of letters compared with previous versions. Is such a change permanent?

### Fontdiff
![image](https://user-images.githubusercontent.com/13285488/85217238-07d9dd80-b3c1-11ea-81b0-78c952178c48.png)

**Comment by nizarsq** [comment]
This one of the issues to consider it as a high priority to fix.

**Comment by nizarsq** [comment]
@Chen-TX Thank you filing this bug. I'm closing this bug because NotoSansArabic 2.5 has been revised. Current NotoSansArabic 2.002 looks ok in terms of cut off in the lower part. Please check the font in this directory https://github.com/googlefonts/noto-fonts/tree/master/unhinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf

**Comment by nizarsq** [comment]
2.4 version released, diacritics looks ok.
<img width="1420" alt="Screen Shot 2020-12-04 at 1 28 46 PM" src="https://user-images.githubusercontent.com/22158882/101216598-a470fe80-3634-11eb-80ae-c82b39f3d7bd.png">
