### ISSUE TITLE
could not type using noto sans kaithi ttf

### ISSUE THREAD

**Issue by raviiya** [googlefonts/noto-fonts#1798]
i could not use noto sans kaithi on my laptop. i have fonts installed but when i type something and press spacebar or enter key the font autoatically changes to default system or app font. how to fix this problem?

**Comment by marekjez86** [comment]
One needs to have Kaithi keyboard installed (having a font is not enough). Look for Kaithi keyboard and switch to it. If not available then the only way I know is to enter hex codes on Windows and Mac (and this is slow since you need to know Unicode codepoint values)... I'm not sure how to do it on the phone.
