### ISSUE TITLE
Font "Linear A" not supported on Windows XP

### ISSUE THREAD

**Issue by Binary-Hazard** [googlefonts/noto-fonts#2045]
What is the least OS that can be supported?

**Comment by fitojb** [comment]
What do you mean, “not supported”? If I install a modern Unicode application like LibreOffice on XP, I can use any code point.

**Comment by Binary-Hazard** [comment]
When I installed it on my Windows XP VM, i opened notepad and I selected the Linear A Noto Font. I copied from internet some Linear A Unicode characters... and tofu appeared? I tried also on Windows Vista: it worked! So, is Windows Vista the least OS that can be supported?

**Comment by fitojb** [comment]
That’s why I mentioned using certain updated applications (instead of system utilities). If you install those fonts under that platform, you need to use fairly recent software, like LO, or Firefox, or Notepad++, to view text. XP SP3 was compiled in 2006 and Unicode back then did not yet support the Linear A code block (it was encoded in 2010 IIRC).

**Comment by Binary-Hazard** [comment]
Ok, thx

**Comment by Binary-Hazard** [comment]
So, there is a non-needed new issue: how to display all Unicode chars together in Notepad? Answer: no. There isn't a font format wich can render all of Unicode chars (143859 in 13.0) together, up to 65536. The only way is to use multiple fonts at one time. That's impossible on Notepad. In two words, Notepad sucks.

**Comment by fitojb** [comment]
I guess you can file a feedback item to suggest Microsoft to add multi-font support to Notepad in a future Windows 10 version
