### ISSUE TITLE
Missing small and capital ligature "dz" and "dzs" from Old Hungarian font

### ISSUE THREAD

**Issue by tamasbartos** [googlefonts/noto-fonts#2054]
## Defect Report
Missing "d"+"z" and "d"+"zs" ligatures from NotoSansOlďHungarian font.

### Character datas
  dz::uni10CC7_10CEF= U+10CC7 + ZWJ + U+10CEF
  dzs: uni10CC7_10CF0 = U+ 10CC7 + ZWJ + U+10CF0
and these capital pairs.

### Font 
  NotoSansOldHungarian-Regular,
Version 2.002, GOOG
 
### Where the font came from, and when
 Site: https://github.com/googlefonts/noto-fonts/blob/main/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
Date: 2021.04.03.

**Comment by tamasbartos** [comment]
@rovasinfo Please upload screenshot about Old-Hungarian "dz" and "dzs"  letters.

**Comment by tamasbartos** [comment]
@marekjez86 Remark: these ligature are non-historic ligatures, too.

**Comment by rovasinfo** [comment]
> @rovasinfo Please upload screenshot about Old-Hungarian "dz" and "dzs" letters.

This ex libris shows the first variants of DZ, DZS from 1935 created by Verpeléti Kiss Dezső (conference book, 2008, ISBN 978-963-87967-5-2 p 120

![verpeleti1935](https://user-images.githubusercontent.com/81823602/113514872-4cf68700-9571-11eb-9283-8536f0b191f0.JPG)

Current use, and explanation why D+Z is not equal to DZ and D+ZS is not equal to DZS.
http://rovas.info/2011/10/betalkalmazasok-dz-dzs/

![kadzomanc](https://user-images.githubusercontent.com/81823602/113514934-ad85c400-9571-11eb-9a1c-14eb0abca794.jpg)

**Comment by tamasbartos** [comment]
@marekjez86 Dear Marek Jezoriek, leader developer of noto-fonts !
Please comment on whether the following ligatures and letters can be inserted into the Unicode Old Hungarian code block:
"q", "x", "w", "y", "dz", "dzs" 
The requested codes by @rovasinfo are the follows (1st is the capital one, 2nd is the small one)  :
"dz" U+10CB3, U+10CF3
"dzs" U+10CB4, U+10CF4
"w" U+10CB6, U+10CF6
"y" U+10CB8, U+10CF8
requested codes of "q", "x" by @rovasinfo I couldn't find.
These code points are reserved code points in the Old Hungarian chart:
[Unicode Old Hungarian chart](http://unicode.org/charts/PDF/U10C80.pdf#page=2)
These letters and ligatures are not part of the Old Hungarian chart:
[Unicode Old Hungarian chart](http://unicode.org/charts/PDF/U10C80.pdf#page=2)
The development of the Old Hungarian font within the noto-fonts project depends on your opinion and clarifies the philosophy of the noto-fonts project.
Please answer as quickly you can.
Regards:
Tamás Bartos

**Comment by rovasinfo** [comment]
Dear @marekjez86 and @tamasbartos 
It is crucial to understand, that these ligatures are not real ligatures, because they are representing different sound values.

Although the historical development of the characters DZ, DZS, Q, W, X and Y is similar to the means of ligature-creation method, these characters are not representing ligatures but individual characters of both the official Hungarian orthography of the Latin script and the so called "Old Hungarian" script.

I added another missing characters to the list which are used on these reserved code points:

"dz" U+10CB3, U+10CF3
"dzs" U+10CB4, U+10CF4
"q" U+10CB5, U+10CF5
"w" U+10CB6, U+10CF6
"x" U+10CB7, U+10CF7
"y" U+10CB8, U+10CF8

Code chart (detail) with requested _de facto_ used characters:

![Old Hungarian Proposed codepoints](https://user-images.githubusercontent.com/81823602/114277523-d6073580-9a2b-11eb-9a84-4c705387648b.JPG)

I hope the Noto font will support this contemporary and living script with the abovementioned  codepoints. The Noto font will be successful if it fully correlate with the extended Hungarian latin based alphabet: https://en.wikipedia.org/wiki/Hungarian_alphabet

**Comment by tamasbartos** [comment]
@marekjez86 @rovasinfo The task of the noto-fonts project is not standardization  but the application of the Unicode standard. 
Although the standard does not  prescribe  mandatory ligatures, I propose compromisse. Ignore issue #2021 , add "dz", and "dzs" as ligatures, as I defined. Additionally define two v ligature as discrete ligature.

There is another font, which use another codepoints for using @rovasinfo's ligatures and letters. I will upload this font's codechart tomorrow.

**Comment by robihorvath** [comment]
@rovasinfo As I know, there are two variant of keyboard layout for Old Hungarian script on Linux, whithin the extras. Unfortunately the ZWJ-extended one's sort description not yet translated to Hungarian language, as I know. But the keyboards revision 2.31 extends the numpad with ZWJ  and ZWNJ keys  on the 3rd level. That wich is wich, I don't know.
On the direct ZWJ-extended layout  the position ZWJ  is the 1st key on the 1st line (position of 0 in latin based Hungarian layout)
