### ISSUE TITLE
Kannada Serif issue where the 'ra' is added after a conjunct,

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#2152]
Greetings from Bengaluru, Karnataka! My heartfelt thanks to your team for working on a very elegant font for Kannada. I tried a few letter combinations, particularly some of the tricky conjuncts and all but one appeared to be fine:

Words like ಶಾಸ್ತ್ರ and ರಾಷ್ಟ್ರ where the 'ra' is added after a conjunct, it is almost hidden. A few screenshots:
![image-01-top](https://user-images.githubusercontent.com/13322623/135683313-40aa34f9-b54a-4d70-bad7-40770315c793.png)

It should actually look like this:
![image-02-bottom](https://user-images.githubusercontent.com/13322623/135683364-3f2e06f7-36b7-49e5-84c6-c5d04c759c53.png)

Hope you can make the necessary change.Thanks and regards,Hari- [...] Author-Designer-Violinist Contributing Editor

**Comment by marekjez86** [comment]
More from Hari- [...] Author-Designer-Violinist Contributing Editor:
------------------------------------------------------------------

Here is the list of all words that I sent:
1. ಶಾಸ್ತ್ರ
2. ರಾಷ್ಟ್ರ
3. ಕ್ಷಿಪ್ರ
4. ಕ್ಷೀರ
5. ವಿನ್ದ್ಯ
6. ಅನ್ತ್ಯ
7. ಕೃತ್ಸ್ನ

#6 alone doesn't look correct in Noto Sans Kannada. The rest look fine.

As for Noto Serif Kannada, #1, #2, and #6 don't look right when I tried in the specimen page on Google (https://fonts.google.com/noto/specimen/Noto+Serif+Kannada) and in Microsoft Word but all seven don't look right when I tried using them in Adobe InDesign (even after switching to world-ready paragraph composer).

Hope this helps.

Best wishes,
Hari

**Comment by sridatta1** [comment]
When the above string is pasted in the following page 
https://fonts.google.com/noto/specimen/Noto+Serif+Kannada
The seems to be fixed 
![image](https://user-images.githubusercontent.com/23263723/142726887-761d1b3a-6cc3-4158-878e-157f76abe4a0.png)


When tested using the font downloaded from the same page 
https://fonts.google.com/download?family=Noto%20Serif%20Kannada
The issue is seen
![image](https://user-images.githubusercontent.com/23263723/142726921-e780c39d-b6bc-4efb-adc1-e8dfcb8f59f6.png)

The issue is not seen ( or it is fixed) in the fonts in the git repo
https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSerifKannada
![image](https://user-images.githubusercontent.com/23263723/142727008-1ed0c4eb-4aeb-4c32-b356-75625667b760.png)
So the latest fonts may be updated in the Download section in the https://fonts.google.com/noto/specimen/Noto+Serif+Kannada webpage

**Comment by sridatta1** [comment]
This issue can be closed
