### ISSUE TITLE
Contextually mispositioned ijam on lam in Noto Nastaliq Urdu

### ISSUE THREAD

**Issue by dscorbett** [googlefonts/noto-fonts#2181]
### Font
NotoNastaliqUrdu-Regular.otf

### Where the font came from, and when
Site: https://raw.githubusercontent.com/googlefonts/noto-fonts/29aa92a9a0768be2d58cf4c590adb5c18b8247c6/unhinted/otf/NotoNastaliqUrdu/NotoNastaliqUrdu-Regular.otf
Date: 2021-12-09

### Font version
Version 2.001

### Issue
The ijam above a lam are too high when the lam precedes another lam. When a meem separates the lams, for example, the ijam are positioned correctly.

### Character data
<span dir="ltr">ڷل ڷمل</span>
U+06B7 ARABIC LETTER LAM WITH THREE DOTS ABOVE
U+0644 ARABIC LETTER LAM
U+0020 SPACE
U+06B7 ARABIC LETTER LAM WITH THREE DOTS ABOVE
U+0645 ARABIC LETTER MEEM
U+0644 ARABIC LETTER LAM
ࣇل ࣇمل
U+08C7 ARABIC LETTER LAM WITH SMALL ARABIC LETTER TAH ABOVE
U+0644 ARABIC LETTER LAM
U+0020 SPACE
U+08C7 ARABIC LETTER LAM WITH SMALL ARABIC LETTER TAH ABOVE
U+0645 ARABIC LETTER MEEM
U+0644 ARABIC LETTER LAM

### Screenshot
![ڷل ڷمل ࣇل ࣇمل](https://user-images.githubusercontent.com/1124347/145447853-256c6841-9294-4c72-a5a4-169c27d7fe5e.png)

**Comment by simoncozens** [comment]
This turns out to be trickier than expected. The anchor points for LamIni.low are placed with the expectation that the next character is going to be a medial/final kaf:

<img width="120" src="https://user-images.githubusercontent.com/106728/151327565-2878e77e-dabb-41e0-b746-8745831debe3.png">

(This is a nice idea but it even fails when gaf is used instead:
<img width="120" src="https://user-images.githubusercontent.com/106728/151327828-5739cfc3-fd30-4d99-8e31-6a6c7e5df03a.png">)

So there are two problems: one is that the anchors aren't even great for what they're meant to be doing; the second is that the low LamIni is being used in the wrong place.
