### ISSUE TITLE
Drawing Cypro-Minoan

### ISSUE THREAD

**Issue by Mercury13** [googlefonts/noto-fonts#2199]
Managed to find a simple and stylish look for Cypro-Minoan. My script for simplicity is monospace and fits into square 800×800, and total character’s size is 1000×1000. Should I contribute, and if so — how?

Unlike Dives Akuru, which is Indic script and I don’t know where to get references and how to put vowel marks correctly, Cypro-Minoan is technically straightforward and well-classified despite lack of inscriptions.

![image](https://user-images.githubusercontent.com/10164882/147893258-f7095f7b-d4be-475c-a248-9602ba88c5c1.png)

**Comment by verdy-p** [comment]
*Cypro-Minoan* is only found in epigraphic sources. Epigraphists prefer using facsimile of their rare relics, than relying on "simplications" which may have many variations (across regions and epochs) still not studied enough and still not compltely unifiable with a single design of glyphs in a font. My be your proposal fits jsut a few of the epigraphic sources you used. It would be interesting to see other facimiles used in the initial encoding for the UCS by ISO/IEC/Unicode: there are probably other characters in discussions at ISO (for which no clear agreement was found and whose encoding is left for later), and the script is probably not completely encoded enough to make a reliable and usable font that would satisfy epigraphics, then students and linguists in someuniversities, and may be some book printers (for now they can still use facsimiles, more or less accurately reproduced "as is" from depicted relics, plus some specific sets of glyphs used by epigraphists to discuss them in their research articles, papers or prints).

Consider the long time it took for African scripts (notably Tiginagh which has a very long history over a very wide area in contact with multiple cultures using very different scripts, but that influenced it to create many variations, including for many variations of Berber languages): Tifinagh could be encoded only because it has an active standard used in Morocco (but there are multiple other variants still needing development in Noto fonts, and still without well-defined OpenType features, or no well-defined Unicode variant sequences).

The same would likely occur in Cypro-Minoan, except that it has no standard form agreed: the current encoding could just be based on what is found in the largest collection of epigraphs from museums in Greece, but other Minoan relics are probably spread all around the Mediterranean Sea (possibly not studied, due to existing economic or political turmoil in some countries and with various states of conservation) or in private collections around the world (not studied publicly).

*Dives Akuru* may be easier to standardize (yes it has diacritics, but there's still the need to talk about required OpenType features for their correct placement, and possibly good rules for composing conjoined letters or specific forms of base letters modified by the specific attachment of some diacritics) because it still has an active use for cultural purposes in the Maldives and the script is much more exposed and better known by more people (it is not jsut on old epigraphic relics like, burial stones, old coinage, or antique buildings and statues more or less degraded over time).

**Comment by Mercury13** [comment]
@verdy-p This is just a screenshot from FontForge. There’s a small part of Dives Akuru visible there, and it is working just for text samples of my program Unicodia. I don’t even know how to put anchors: on others’ fonts it works, but when I add my own anchors, nope. And Dives Akuru has >1000 years of recorded history, and all this time it evolved, so I don’t know whether my drawings are historically correct (probably no). Encoding scheme is murky, every attempt to deviate from reference pictures make me ask questions: am I doing right? And I don’t just know where to find references, every search returns one or two pictures, and period.

And in Cypro-Minoan I of course looked into others’ outlines, and into actual facsimiles, as they are just easily available. George Douros recently made his Aegean fonts non-free but he still did great job.

**Comment by verdy-p** [comment]
Thanks for your notes. Still what I said was absolutely not a criticism, your work is interesting as it is a base version on which other details can be developped or tuned, beacause we have a comparison. Now it's time to look for other references and detect those differences, and discuss how to support them (e.g. with OpenType placement or substitution rules, or with linguistiic features for variants, or later maybe with encoding as Unicode variants, when these will have been experimented and proposed for encoding if they are needed: the initial encoding in Unicode/ISO/IEC 10646 is still at a preliminary stage and it is not finished, jsut like the encoding of any other supported scripts which regularly have additions when there's a demonstrated need and an agreed convention). Anyway to get such convention, the script must still find its community of users to make decent proposals that satisfies at least a significant number of them.
