### ISSUE TITLE
Two Tibetan banned chars are garbled

### ISSUE THREAD

**Issue by Mercury13** [googlefonts/noto-fonts#2311]
### Title 
Tibetan 0F77 and 0F79 are garbled

(they are banned and should not exist in actual text, but is it possible to showcase them somehow?)

### Font 
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
Site: this repo
Date: 2022-04-07

### Font Version
2.101

### OS name and version
Win10 21H1

### Application name and version
Qt 6.1.2, probably all OS

### Issue
  1. Draw 25CC+0F77, 25CC+0F79
  2. Look badly
  3. Should look good

### Character data
25CC Dotted circle
0F77 Tibetan vowel sign Vocalic Rr

25CC Dotted circle
0F79 Tibetan vowel sign Vocalic Ll

### Screenshot
![image](https://user-images.githubusercontent.com/10164882/162073431-b8cd8867-7678-4859-8aa0-0123fa713f20.png)
![image](https://user-images.githubusercontent.com/10164882/162073465-43404f88-872a-4f7c-adda-e247e36e630c.png)

**Comment by simoncozens** [comment]
The problem is due to the ordering of features. `blwm` contains the mark-to-mark positioning rules but this is being run before `mark` which contains the mark-to-base positioning rules. So the two below marks are first being correctly positioned relative to each other, and then erroneously attached to the same base glyph. Giving these features an explicit ordering seems to fix it.

![shape](https://user-images.githubusercontent.com/106728/162077338-1371bd49-975b-4cb0-a0e7-5f513bfea18f.png)
