### ISSUE TITLE
The difference between thick and thin lines on the Noto Serif Display is extreme.

### ISSUE THREAD

**Issue by Hackgets** [googlefonts/noto-fonts#2352]
### Title 
  The difference between thick and thin lines on the Noto Serif Display is extreme.

### Font 
  NotoSerifDisplay-*.ttf

### Font Version
  2.007

### OS name and version
  Windows 10 Home 21H2

**Comment by simoncozens** [comment]
It is, but this is by design; it's what makes it the display version of the font, rather than a font for running text use. (You can use Noto Serif as a less "extreme" version instead.) So this is a deliberate choice, not a bug.

**Comment by fitojb** [comment]
FYI, in typography, this feature is called stroke contrast. Serif typefaces that exhibit a high contrast are sometimes called *stressed* or have “display” in their names, because they’re aimed to be used in large sizes.

**Comment by fitojb** [comment]
FYI, in typography, this feature is called stroke contrast. Serif typefaces that exhibit a high contrast are sometimes called stressed or have “display” in their names, because they’re aimed to be used in large sizes.

To be fair, it’s a bit unexpected for Serif Display to feature much more contrast than Sans Display. :)
