### ISSUE TITLE
Noto Sans Thai: U+F700 and U+F70F are missing

### ISSUE THREAD

**Issue by phatham** [googlefonts/noto-fonts#2372]
### Title 
U+F700 and U+F70F, commonly used for displaying Tho Than with no base and Yo Ying with no base, are missing.

### Font 
NotoSansThai-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/master/hinted/ttf/NotoSansThai/NotoSansThai-Regular.ttf
Date: 2022-06-01
Commit: https://github.com/googlefonts/noto-fonts/commit/7cc5db35775d78c7def56b582c7f740d0768820d

### Font Version
Version 2.000; ttfautohint (v1.8) -l 8 -r 50 -G 200 -x 14 -D thai -f none -a qsq -X ""

### OS name and version
Windows 10 Version 21H1 (OS Build 19043.1706)

### Issue
Tho Than `ฐ` and Yo Ying `ญ` with no bases (`` and ``, respectively) could not be displayed. The unicode points for those with no bases are `U+F700` for Tho Than with no base and `U+F70F` for Yo Ying with no base. When regular Tho Than (U+0E10) or Yo Ying (U+0E0D) combines with another character below them, for example, Sara U (U+0E38), its base will be cut off.
`ฐ` +`ุ` => `ฐุ`
`ญ` +`ุ` => `ญุ`

Those characters with no base should be able to be displayed without requiring another character below them using unicodes U+F700 and U+F70F. These unicode points for Tho Than and Yo Ying with no bases are defined in other fonts, such as Arial Unicode MS, TH Sarabun New and TH Baijam.

### Character data
For Tho Than with no base, the glyph `uni0E10.less` should have the unicode of `U+F700`.
For Yo Ying with no base, the glyph `uni0E0D.less` should have the unicode of `U+F70F`.

### Screenshot for Current Issue

![](https://user-images.githubusercontent.com/45591865/171467023-9e8b758e-0b4b-4b4e-8f63-191a2b3f7152.jpg)

### Screenshot for Expected Outcome

![](https://user-images.githubusercontent.com/45591865/171467400-8210845e-a48e-4270-b3f7-b29e15556712.jpg)

**Comment by ohbendy** [comment]
F700 and F70F are private use characters, I can only assume some legacy fonts include the .less versions of thoThan and yoYing in those slots if they don't support OpenType. 

The Noto fonts use OpenType to automatically substitute the .less versions if a) any below-base marks are present or b) if the text is tagged as Pali language. 

Are there other situations where the .less versions would be used?

**Comment by phatham** [comment]
Yes, mostly when handling with Pali-Thai language:
1. In some situations where both regular Thai and Pali are typed together, thoThan and yoYing with .less versions are preferable in one place, but not preferable in another.
2. In some legacy documents (for example, https://84000.org/tipitaka/read/pali_read.php?B=1&A=1&w=&modeTY=1&pagebreak=), the private use characters are used to display thoThan and yoYing with no base.
3. In many situations where texts cannot be tagged as Pali language, U+F700 and U+F70F are used as a convention.

**Comment by ohbendy** [comment]
One possibility might be to put the .less versions in a stylistic set (more broadly accessible than language tagging). That way the glyphs would still point back to the original codepoints 0E10 and 0E0D but the appearance would be correct. Does your software enable stylistic sets?

**Comment by phatham** [comment]
Thank you for your response. I primarily use Latex-based software for text rendering, which I am pretty sure that there is no problem on selecting the stylistic set or selecting languages. However, many users still use MS-related software, which there is no convenient way to display mixed characters without using PUA characters.

Including .less versions in a stylistic set is an interesting approach if assigning PUA codepoints will make the font nonstandard, as stylistic sets are selectable in MS-related software via. the Font menu.

**Comment by davelab6** [comment]
The Noto project is dedicated to unicode so we won't do PUA encoding.

**Comment by phatham** [comment]
@davelab6 Thank you for clarification. Then is it possible to include .less versions in a stylistic set as @ohbendy suggested?

**Comment by simoncozens** [comment]
Yes, I’ll get these added to a stylistic set.

**Comment by ctrlcctrlv** [comment]
I can help you co-author a proposal for the Unicode Technical Committee. It'll go to the Script Ad Hoc first. Let me know if this interests you.

You need documentary evidence that these characters create a _clear distinction_ in meaning in a language for the proposal to succeed.

**Comment by ohbendy** [comment]
(I personally don't support the inclusion of those in Unicode, I see the .less versions purely as a graphic difference, not a character difference, they're still yoYing and thoThan. Encoding them separately would mean users would need a different keyboard for Pali, fonts without the new characters would just display .notdef instead of reverting to the normal glyphs, and the potential for accidental misuse in Thai language is too great.)

**Comment by NorbertLindenberg** [comment]
> One possibility might be to put the .less versions in a stylistic set (more broadly accessible than language tagging). That way the glyphs would still point back to the original codepoints 0E10 and 0E0D but the appearance would be correct.

The font could support both: selection by language for applications that support it (such as web browsers); stylistic sets for those less fortunate.

**Comment by ohbendy** [comment]
yes, sorry, I meant in addition to, not instead of, language tagging :-)

**Comment by phatham** [comment]
I had consulted with a local Thai-Pali expert. Those ThoThan and YoYing with or without bases have the same meaning. The bases are cut off for the sake of readability.

@simoncozens, @ohbendy and @NorbertLindenberg: stylistic set and language tagging will definitely make the font(s) more usable. For example, stylistic set in some desktop applications and `<p lang="pi">...</p>` or  `<p lang="sa">...</p>` for web-based display.

@ctrlcctrlv maybe a variation/display proposal would be more suitable because the meanings for the ones with base and no base are the same (not distinct characters). However, I don't know whether this is in Unicode's scope or not.

**Comment by ctrlcctrlv** [comment]
> I had consulted with a local Thai-Pali expert. Those ThoThan and YoYing with or without bases have the same meaning. The bases are cut off for the sake of readability.

So a character proposal would not be appropriate, per @ohbendy.

> @ctrlcctrlv maybe a variation/display proposal would be more suitable because the meanings for the ones with base and no base are the same. However, I don't know whether this is in Unicode's scope or not.

I'll look into it, whether this is such a case. @lianghai is there any similarity between this case and the Variation Sequences you propose for Mongolian? They seem similar to me, but I could be wrong.

**Comment by lianghai** [comment]
> I see the .less versions purely as a graphic difference, not a character difference, they're still yoYing and thoThan.

> I had consulted with a local Thai-Pali expert. Those ThoThan and YoYing with or without bases have the same meaning. The bases are cut off for the sake of readability.

These analyses are a bit ambiguous. The question is whether the descendered forms are acceptable in Pali texts.

- If they’re acceptable, but just not preferred (cf, Bulgarian preference of Cyrillic letterforms), we can rely on OTL locl and ssXX.
  * Language tagging and OTL locl are never reliable enough for what matters more.
- But if they’re not acceptable (a classic case of “not acceptable” is that in IPA, mixing single- and double-story “a” is not acceptable), there should be an encoding-level solution.
  * Because (as @ohbendy already emphasized) it may be harmful for Thai texts if we encoding new characters, this may be one of the few cases where standardized variation sequences are actually worth considering.
  * But also, consider U+0251 ɑ LATIN SMALL LETTER ALPHA and U+0261 ɡ LATIN SMALL LETTER SCRIPT G, have they been poluting day-to-day Latin texts? It’s a topic worth discussing.

> @lianghai is there any similarity between this case and the Variation Sequences you propose for Mongolian? They seem similar to me, but I could be wrong.

@ctrlcctrlv, never refer to the Unicode Mongolian encoding (the single worst encoding model in Unicode), unless you’re already a Mongolian encoding expert.

**Comment by ohbendy** [comment]
As Liang suggests, it's a matter of what's acceptable in Pali texts. I believe the full versions would still be readable/intelligible, just not preferred. But it's a bit hard to know since historically Pali texts in Thailand would not be written in Thai script but Tham script. I think the key would be to listen to Pali users in Thailand before trying to 'help' ;) 

> consider U+0251 ɑ LATIN SMALL LETTER ALPHA and U+0261 ɡ LATIN SMALL LETTER SCRIPT G, they don’t seem to be polluting day-to-day Latin texts, right? Why is that? It’s a topic worth discussing.

Good to consider. Perhaps because those letters are not in the same block as basic Latin, it's a bit harder to accidentally pick them from a character picker (and also because most fonts don't contain them)

**Comment by ctrlcctrlv** [comment]
> @ctrlcctrlv, never refer to the Unicode Mongolian encoding (the single worst encoding model in Unicode), unless you’re already a Mongolian encoding expert.

This got a good laugh from me. Indeed when I'm reaching for Mongolian for precedent I'm probably reaching too far...
