### ISSUE TITLE
Noto Sans Gurmukhi glyph overlapping occurring with PAIRIN HA and PAIRIN VA

### ISSUE THREAD

**Issue by kulpreetchilana** [googlefonts/noto-fonts#388]
Glyph overlapping occurring with PAIRIN HA and PAIRIN VA, when combined with with U+0A41 U and U+0A42 UU:

![screen shot 2015-06-14 at 9 09 10](https://cloud.githubusercontent.com/assets/235441/8152967/a50c7920-12d9-11e5-8273-3a7bce006225.png)

**Comment by fontguy** [comment]
cc @waksmonskiMT

**Comment by JelleBosmaMT** [comment]
This is a feature not a bug. These combinations are not frequent. Out of a list of 60000 Panjabi words, I found 1 occurrence of subscript ha with uu and 1 of subscript va with uu and none with the u. To accommodate these without touching there is a choice for unpractical large line to line distances for the extremely rare case that these 2 words are used. Or accept the the lower marks are invisible because they are clipped or overlap with marks of the next line in the text. Having a ligature is the lesser evil.
