### ISSUE TITLE
Svarita preceeding visarga not rendered correctly

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#424]
Moved from googlei18n/noto-alpha/issues/284

Imported from Google Code issue #284 created by vvasuki@google.com on 2015-06-02T18:14:16.000Z:

Some lines in the Rigveda text http://www.detlef108.de/RV-D-UTF8.html are not rendered correctly. In particular, consider: [स न॑ः पि॒तेव॑]

This is what it looks like with Noto Sans: http://i.imgur.com/jocRriY.png
## This is what it looks like with Chandas : http://i.imgur.com/PqyVQ1i.png

Comment #1 originally posted by cibu@google.com on 2015-06-03T16:06:51.000Z:

I don't think Noto Devanagari is really designed for vedic. However, there are some low hanging fruits like this could be corrected.

**Comment by JelleBosmaMT** [comment]
The dotted circle is inserted by the rendering software to indicate an invalid combination. This happens at the level of Unicode characters. This is not a font issue, but of the software used to render the text.

**Comment by nizarsq** [comment]
@marekjez86 looked at 'न॑ः पि॒तेव॑]' using NotoSansDevanagari, I compared the current rendering in NotoSansDevanagari against https://i.imgur.com/jocRriY.png they both render U+0903 (ः) the same. I'm not sure what is the expected behavior or the issue? I also tested the text with 3rd party fonts and they all render U+0903 (ः) same.
<img width="1026" alt="Screen Shot 2020-07-31 at 1 39 55 PM" src="https://user-images.githubusercontent.com/22158882/89075551-528d3480-d333-11ea-999a-c86cfdbd55c9.png">

**Comment by ujjvlh** [comment]
The Visarga sign ought to be added before the Svarita sign. This is as per most Unicode texts I have seen. Otherwise most fonts will render incorrectly. Thus, this is the correct way to write:

स नः॑ पि॒तेव॑ सू॒नवे॑।

**Comment by simoncozens** [comment]
This was a problem with the encoding of the Rigveda text on the web site, which I notice has now been fixed there; not a font bug.
