### ISSUE TITLE
Sinhala: sub-optimal placement of repaya in complex conjunct

### ISSUE THREAD

**Issue by mjansche** [googlefonts/noto-fonts#523]
In the word ආර්‍ය්‍ය, the repaya glyph is currently being placed above the yansaya glyph. It would be better to place it immediately above the consonant that logically follows repaya (i.e. the full ya glyph). Perhaps this is best illustrated by the output of hb-view from the HarfBuzz master branch. Here is how the text ආර්‍ය්‍ය (0D86 aa; 0DBB 0DCA 200D repaya; 0DBA ya; 0DCA 200D 0DBA yansaya) renders in NotoSansSinhala-Regular.ttf (md5sum: b177716c7ff95c385902dba9d3b0b5ad):

![aaryya_noto](https://cloud.githubusercontent.com/assets/11460451/10171825/f2790fa4-66d3-11e5-9e8b-8d32efdc5bb7.png)

Compare this with how the same text is rendered with the LKLUG Sinhala font (e.g. in Debian/Ubuntu package fonts-lklug-sinhala; md5sum: 96b2f06cf1cf4e436ec46198d4bc61f2):

![aaryya_lklug](https://cloud.githubusercontent.com/assets/11460451/10171662/173067d0-66d3-11e5-8571-c4fa119610fd.png)

According to one native speaker, both renderings are understandable but the LKLUG rendering is preferred.

**Comment by roozbehp** [comment]
Confirming the bug in Noto. Windows fonts Nirmala and Iskoola Pota also display the repaya over the ya.

**Comment by JelleBosmaMT** [comment]
Rendering of Noto is inspired by the BhashitaComplex fonts, distributed by ICTA as model fonts with correct rendering. These fonts have ligatures with rephaya on the post-base ya, including complete ligatures for the depicted sequence. ICTA being an agency of the Sri Lanka government, it seemed best to follow the given example.

**Comment by roozbehp** [comment]
@JelleBosmaMT It seems that the Sri Lankan national standard SLS 1134 (section 5.7, page 15 of http://www.unicode.org/L2/L2004/04131r-sls1134.pdf) shows the repaya over the ya. It shows it the same way in a newer revision too ([SLS 1134 2011 v3.41.pdf](https://github.com/googlei18n/noto-fonts/files/4678/SLS.1134.2011.v3.41.pdf)).


@tiroj Do you have any information on this subject?

**Comment by tiroj** [comment]
Roozbeh, there actually seems to be a discrepancy between the two versions of the SLS 1134 document. If you look closely at the example on page 15 of the 2004 version, you see the rephaya on the postscript -Ya glyph; in the 2011 version (page 24) the rephaya is on the full Ya consonant glyph.

Do you have contact with the Sri Lankan national body via Unicode? I would be inclined to ask for a statement on this.

**Comment by roozbehp** [comment]
@tiroj You're right. I have no idea how I saw the repaya in the 2004 version on the ya! I guess I was so convinced I ignored my own eyes!

Re Unicode contact, there's a liaison with ICTA (Information and Communication Technology Agency of Sri Lanka), Dr Gihan Dias. Various public Unicode documents lists his email as gihan@icta.lk and gihan@uom.lk. @xiangyexiao/@marekjez86, would you please reach him for advice?

**Comment by JelleBosmaMT** [comment]
Gihan Dias has been involved with the Bhashida font. If you supply
complete ligatures there is no rendering issue with some shapers putting
the rephaya in front of the yansaya and others behind the yansaya. Of
course Dr Dias has authored both versions of the standard document too.

In both documents the font being used is Iskoola Pota. Windows 7 renders
the rephaya on ya. Windows 8.1 on Yansaya (Iskoola Pota and Nirmala). This
suggest that Uniscribe has been updated regarding re-ordering. I think
Noto Sans handles either ordering with repaya on yansaya.

Please note the wording of the two document versions:

2004:  A yansaya with repaya (in words such as ක යර ලය)

2011:  A ya followed by a yansaya with a repaya

It does NOT say "a ya with rephaya followed by yansaya” ! It describes
what codes to use, to get the rephaya on the yansaya. In 2004 the coding
bypasses the shaper re-ordering, by skipping over the first ya.

The reason why the rephaya is on the yansaya in 2004 is that its is
encoded with a ZWNJ. Rather than writing r-y-ya, the sample word is
spelled y-r-ya, with various joiners and non-joiners to force repaya and
yansaya glyphs. 

The reason why the rephaya is on ya in 2011, is because the font is
Iskoola Pota and that is how it rendered in 2011 when spelling r-y-ya.
Today it does differently.

Jelle

**Comment by marekjez86** [comment]
Given the discussion in the report here. In particular:
- "Rendering of Noto is inspired by the BhashitaComplex fonts, distributed by ICTA as model fonts with correct rendering"
- "Gihan Dias has been involved with the Bhashida font."
- ... and others from Jelle
I'm leaning toward opinion that this is not an issue and the look of the current Noto is as designed. However, I'll reach out to Gihan Dias.
@mjansche, would you agree that this is as designed?

**Comment by mjansche** [comment]
Yes, I agree that this looks as designed. Thanks for the clarification about the two different revisions of the SLS doc and for the pointer to the BhashitaComplex fonts.

I'll note in passing that the visual placement of repaya varies for different values of C in the sequence repaya C yansaya. The repaya appears above yansaya iff C == ya; otherwise it appears above the consonant C, e.g. for C == ta in මර්‍ත්‍ය. Looking e.g. at various entries in [Clough's dictionary](https://ia802205.us.archive.org/8/items/sinhaleseenglish00clourich/sinhaleseenglish00clourich.pdf) corroborates this.

**Comment by tiroj** [comment]
Thanks, @mjansche: that sounds like a clear and implementable rule. It would be nice to get confirmation of this from Gihan Dias, just in case we're missing any additional aspect, but presuming this is correct I can get updates done on the Microsoft fonts to standardise this behaviour.

**Comment by roozbehp** [comment]
@marekjez86, it seems that the informed consensus is that this is WAI. But it would be very nice to confirm with Dr Dias and get extra information on preferences.

**Comment by pathumego** [comment]
cc @paarandika @pushpananda

**Comment by JelleBosmaMT** [comment]
On 01-okt.-15 01:02, "Martin Jansche" <notifications@github.com> wrote:

>I'll note in passing that the visual placement of repaya varies for
>different values of C in the sequence repaya C yansaya. The repaya
>appears above yansaya iff C == ya; otherwise it appears above the
>consonant C, e.g. for C == ta in මර්‍ත්‍ය. Looking e.g. at various
>entries in Clough's dictionary
><https://ia802205.us.archive.org/8/items/sinhaleseenglish00clourich/sinhal
>eseenglish00clourich.pdf> corroborates this.


If in conjuncts with yansaya the postion of repaja depends on the base,
then Noto has a problem: it will always place it on the yansaya.

**Comment by mjansche** [comment]
The position of repaya does seem to vary in practice and in BhashitaComplex it appears to depend on the base consonant. Here is the word මර්‍ත්‍ය in Clough's dictionary [p. 461, second column, third lemma](https://ia802205.us.archive.org/BookReader/BookReaderImages.php?zip=/8/items/sinhaleseenglish00clourich/sinhaleseenglish00clourich_jp2.zip&file=sinhaleseenglish00clourich_jp2/sinhaleseenglish00clourich_0941.jp2&scale=1&rotate=0) and rendered in LBhashithaComplex:

![martya](https://cloud.githubusercontent.com/assets/11460451/10219388/6f068ad4-6836-11e5-82f2-5e413d5efc08.png)

**Comment by mjansche** [comment]
A few more examples: Dharmya ධර්‍ම්‍ය [Clough, p. 269](https://ia802205.us.archive.org/BookReader/BookReaderImages.php?zip=/8/items/sinhaleseenglish00clourich/sinhaleseenglish00clourich_jp2.zip&file=sinhaleseenglish00clourich_jp2/sinhaleseenglish00clourich_0557.jp2&scale=1&rotate=0);
Saamarthya සාමර්‍ම්‍ය [Clough, p. 677, second column, first lemma](https://ia802205.us.archive.org/BookReader/BookReaderImages.php?zip=/8/items/sinhaleseenglish00clourich/sinhaleseenglish00clourich_jp2.zip&file=sinhaleseenglish00clourich_jp2/sinhaleseenglish00clourich_1373.jp2&scale=1&rotate=0); Harmya හර්‍ම්‍ය [Clough, p. 725](https://ia802205.us.archive.org/BookReader/BookReaderImages.php?zip=/8/items/sinhaleseenglish00clourich/sinhaleseenglish00clourich_jp2.zip&file=sinhaleseenglish00clourich_jp2/sinhaleseenglish00clourich_1469.jp2&scale=1&rotate=0). All appear with the repaya above the base consonant. BhashitaComplex does the same. Here is how LBhashitaComplex puts the repaya deliberately off-center above the "th" in Saamarthya:

![saamarthya](https://cloud.githubusercontent.com/assets/11460451/10220285/0132b5c0-683e-11e5-94e8-99bc2b0055c0.png)

(Of course, another thing that all of these words have in common is that yansaya appears as the last letter in the word. I'm hoping this is just a coincidence and that positioning of repaya won't depend on the position of the consonants within the word.)

**Comment by tiroj** [comment]
"Here is how LBhashitaComplex puts the repaya deliberately off-center above the "th" in Saamarthya:"

සාමර්‍ථ්‍ය, not සාමර්‍ම්‍ය, yes? Here's the Nirmala UI shaping:
<img width="498" alt="screen shot 2015-10-01 at 11 04 57" src="https://cloud.githubusercontent.com/assets/5614500/10229303/592a40de-682c-11e5-96f5-91d6f15ba1bf.png">

At the moment, Nirmala UI (and Iskoola Pota) are also positioning rephaya on the base consonant when the sequence is RY-Ya:
<img width="349" alt="screen shot 2015-10-01 at 11 07 42" src="https://cloud.githubusercontent.com/assets/5614500/10229406/e3c9b044-682c-11e5-80bd-205fa2ee36b1.png">

I did include a postscript -Ya with rephaya ligature in the Nirmala UI font, because this had been part of the old Linotype Araliya set, but at the moment it isn't used.

**Comment by marekjez86** [comment]
This is FYI: I sent out an e-mail couple of days ago to Prof. Gihan Dias, but I got no response so far. Therefore, today I sent out messages to 5 different people on the team he works with at the University in Sri Lanka. I hope that somebody there would respond to my message.

**Comment by JelleBosmaMT** [comment]
![sinh](https://cloud.githubusercontent.com/assets/12729011/10262200/8292eb64-69bd-11e5-9eb1-91214dcb79e2.png)

**Comment by pathumego** [comment]
@marekjez86 I have sent this out to be clarified from Prof. [JB DIssanayake](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=JB+DIssanayake). Will hear from him within next two days.


Although Im am a native reader I am not really familier with the patterns of  `Repaya`. Unlike /Rakaransaya and Yansaya, Repaya is not in common use anymore, you wouldn't see it in literature and common use. 


So, according to Encyclopedia of Sinhala Language and Culture by Prof JB:

```
 Yansaya is the consonant stroke used in the place of the consonant ය, that follows another consonant. (Not Kha, but Kh). So for example  `kh-y ` ඛ්ය becomes `khya` ඛ්‍ය 
```
```
The Repaya is the consonant stroke that is used in place of ර් [R] that precedes a consonant.
```

So I think this is what the behaviour based on Prof JB and my own reading experience. This is seen in 

`
 All the other occurrences (KYa, MYa..) except for `RYa` where both Rephaya are Yansaya is used, Repaya should be on the Base character. In case of `RYa` Repaya should be on Yansaya.
`

This is because, ආර්ය = ආයර්‍්‍ය

This is a non standard behaviour. In case of  ආර්ය  Although the typing sequence is `RY-Ya` it reads actually `RYa`

**Comment by JelleBosmaMT** [comment]
I further investigated this. The Bhashita fonts puts the rephaya on yansaya in 11 combinations. 

![capture](https://cloud.githubusercontent.com/assets/12729011/11534555/9f1da838-990f-11e5-8048-48f818dc9b6a.PNG)

Because Bhashita has a set of rephaya on yansaya ligatures, I came to the conclusion that it was the rule to put them there. But it turns out that the ligatures other than for R-Y-Ya are not referenced in the GSUB. 
As far as my limited linguistic research capability goes, R-Y-Ya is the only syllable that I have been able to find with with both rephaya and yansaya. 
The reason why Bhashita has more combinations is that it does not have a rephaya ligature for all the base consonants. And with ligature the rephaya ends up to the right of the consonant. So there is no intend to put them on yansaya. Maybe these consonants never combine with rephaya, let alone with rephaya and yansaya.
So moving forward I can change the Noto fonts to combine with the base, unless for R-Y-Ya. If any of these combinations exist, it could be an improvement. And if they do not exist, it makes no difference.

**Comment by JelleBosmaMT** [comment]
Preparingnew version as described above

**Comment by nizarsq** [comment]
@marekjez86 look like this is WAI. Any suggestions? current render is same what reported.
<img width="1213" alt="Screen Shot 2020-08-11 at 11 01 08 PM" src="https://user-images.githubusercontent.com/22158882/89980333-8d8e4280-dc26-11ea-817f-48d20bd11b11.png">
