### ISSUE TITLE
chondrobindu in NotoSansBengali

### ISSUE THREAD

**Issue by kmanwar** [googlefonts/noto-fonts#604]
I noticed one problem of NotoSansBengali in rendering "ঁ". e.g. তাঁদের should be rendered like this. 

[tader](https://cloud.githubusercontent.com/assets/738955/12138414/00773976-b483-11e5-9ff0-0c92f361a533.png)

It would be great if we can fix this rendering issue.
.

**Comment by marekjez86** [comment]
@kmanwar I assume that you want to move "ঁ" to the left (see the first line below - I did all in the textedit on Mac with unhinted fonts). Please advise. Note that we are testing and hope to release soon Noto Serif Bengali. If you are open to receiving an early version of it and letting us know if you see and rendering issues, it would be fantastic.

![bengali](https://cloud.githubusercontent.com/assets/13322623/12204707/ae13a1a6-b5ea-11e5-9991-e3a9bceafb0c.jpg)

@waksmonskiMT could we get a correction to Noto Sans Bengali (please see the inconsistency above).

**Comment by TidharC** [comment]
Still repro with Noto Sans Bengali.
Looks correct with Noto Serif Bengali.

**Comment by JelleBosmaMT** [comment]
The shaper software puts the candrabindu after vowel signs. I guess it is nice and correct to have it over the base consonant when there is a long-a or a post base য. For the Noto Bengali Sans MM version I added a font lookup to re-order the candrabindu. So that should fix this issue.

However... because there are many fonts that do not re-order the candrabindu, expectations may have adapted.  It is very well possible somebody will raise a GitHub issue that the Noto does not render like "the Windows fonts" ;-(

**Comment by nizarsq** [comment]
This issue fixed. 
<img width="989" alt="Screen Shot 2020-06-11 at 7 45 13 AM" src="https://user-images.githubusercontent.com/22158882/84400962-8f507100-abb7-11ea-888c-f21b4a7149ad.png">
