### ISSUE TITLE
Noto Sans Batak doesn't reorder as required by Unicode Standard

### ISSUE THREAD

**Issue by NorbertLindenberg** [googlefonts/noto-fonts#624]
The Unicode Standard, section 17.6, specifies a reordering of glyphs in certain situations:

"The main peculiarity of Batak rendering concerns the reordering of the glyphs for vowel signs when one of the two killers, pangolat or panongonan, is used to close the syllable by killing the inherent vowel of a final consonant. This reordering for display is entirely regular. So, while the representation of the syllable /tip/ is done in logical order: <ta, vowel sign i, pa, pangolat>, when rendered for display the glyph for the vowel sign is visually applied to the final consonant, pa, rather than to the ta. The glyph for the pangolat always stays at the end of the syllable."

See
http://www.unicode.org/versions/Unicode8.0.0/ch17.pdf
and for examples
https://en.wikipedia.org/wiki/Batak_alphabet#Diacritic_reordering_for_closed_syllables

The Noto Sans Batak font does not implement this reordering. Note that this is not the kind of reordering that the Universal Shaping Engine takes care of; it must be implemented in the font.

To make matters worse, if the user tries to compensate for this bug by manually entering characters in the desired visual sequence, which is logically invalid because it has a virama directly following a vowel, the Universal Shaping Engine does not flag this sequence as invalid because the Batak viramas are classified as "pure killers".

Steps to Reproduce:
1. Open Firefox.
2. Go to http://lindenbergsoftware.com/google/noto/batak-reordering.html

Expected Results:
In the section "Vowel reordering", the strings should be rendered with the following glyph sequences:
ᯖ ᯇ ᯪ ᯲
ᯖ ᯇ ᯮ  ᯲

Actual Results:
In the section "Vowel reordering", the strings are rendered with the following glyph sequences:
ᯖ ᯪ ᯇ ᯲
ᯖ ᯮ  ᯇ ᯲

See screen shot.

Configuration:
Noto Sans Batak Regular 1.05. Firefox 44.0.1 on Mac OS X 10.11.3.

![batak reordering](https://cloud.githubusercontent.com/assets/216206/12969934/82fa36a8-d03c-11e5-97f9-f9d9d997181a.png)

**Comment by NorbertLindenberg** [comment]
This article describes how to implement Batak reordering in OpenType:
https://lindenbergsoftware.com/en/notes/constructing-fonts-for-batak/index.html#Reordering

**Comment by r12a** [comment]
By the way, the Pangururan font does this reordering for (at least some) vowels, eg. see the text rendered in red here, and compare with the list of codepoints:

![Screenshot 2021-02-26 at 12 31 06](https://user-images.githubusercontent.com/4839211/109300539-86c7c580-782e-11eb-85b1-db06eea76663.png)

https://r12a.github.io/pickers/batk/?text=%E1%AF%85%E1%AF%A9%E1%AF%89%E1%AF%B2%20%20%E1%AF%9E%E1%AF%A9%E1%AF%82%E1%AF%B2 will by default show the noto result. (You can add the Pangururan font by clicking on the F icon, in order to compare.)

Noto gives:

![Screenshot 2021-02-26 at 12 35 01](https://user-images.githubusercontent.com/4839211/109300900-12415680-782f-11eb-93f4-98d2c0ebc0d1.png)

I agree that the problem described is a showstopper for use of Noto's Batak font.

**Comment by punchcutter** [comment]
<img width="204" alt="batak624" src="https://user-images.githubusercontent.com/11257204/126869913-d652470e-5a35-4ee3-a8d8-206165843775.png">
Updated to reorder correctly. Image shows old (top) and new (bottom).

**Comment by simoncozens** [comment]
Sounds like this is now fixed?

**Comment by NorbertLindenberg** [comment]
LGTM
