### ISSUE TITLE
Oriya conjunct issue?

### ISSUE THREAD

**Issue by Kanjilearner817** [googlefonts/noto-fonts#647]
I don't if this is intentional or not and I don't know how to take a screenshot, but for some reason, the conjunct <0B1C + 0B4D + 0B2F> doesn't render in Noto Sans Oriya like it does in Arial Unicode MS, Kalinga, Nirmala UI or Unifont (although Nirmala UI's rendition of this conjunct is also off in its own way).

**Comment by Kanjilearner817** [comment]
This was on Windows 10, by the way.

**Comment by TidharC** [comment]
Can you please include a screenshot?

I tried the same char sequence on Mac OS, and see a rendering difference between Noto Sans Oriya and Oriya (Sangam) MN.

![notosansoriya](https://cloud.githubusercontent.com/assets/16353803/18853533/7ea87f66-83fa-11e6-9b42-1f8460447f37.png)

**Comment by TidharC** [comment]
If you need help taking the screenshot, the following article provides some tips:
http://www.digitalcitizen.life/4-ways-take-screenshots-windows-8-81-using-built-tools
As an alternative, you could also take a photo of the PC screen with your phone.

**Comment by Kanjilearner817** [comment]
Here's a rendering of the name of the Republic of India in Oriya, in Arial Unicode MS, Lohit Oriya, Nirmala UI, Noto Sans Oriya, and Unifont. It doesn't show here, unfortunately, but I've seen fonts connect the glyph for <0B2F> as seen in Lohit, Nirmala and Noto, albeit in a much smaller form, to the glyph for <0B1C>.
![republic of india in odia](https://cloud.githubusercontent.com/assets/13095930/19413667/759ecd38-92e8-11e6-86d3-0ca448d86dfb.PNG)

**Comment by Kanjilearner817** [comment]
I'm not sure why this was assigned to me. I'm not a font designer.

**Comment by dougfelt** [comment]
@Kanjilearner817, it was assigned to you because we needed more information.  Once you provided the screenshot we should have taken your name off.

I'm not sure if you're asserting that Noto (and Lohit and Nirmala) are _wrong_, or just different.  Noto is rendering the same as Lohit and Nirmala in the screenshot you provided.  I don't know Oriya, but it could be that the form is optional, and sometimes the text renders with a 'subscript' form of YA like Oriya MN and Oriya Sangam MN, and sometimes with a variant form as in Lohit and Nirmala.  Arial Unicode is just showing the Virama, which might be an option too.

@waksmonskiMT, can someone at Monotype weigh in about how Oriya handles this sequence and what the typographic options are?

**Comment by nizarsq** [comment]
As mentioned before, NotoSansOriya rendering is the same as Lohit and Nirmala in the screenshot, not sure if this was an issue or was intentional.
The current rendering for 0B1C + 0B4D + 0B2F has been modified since the bug filed. I'm going to close the bug since there is no updates since 2017.
<img width="1117" alt="Screen Shot 2020-06-20 at 10 54 49 PM" src="https://user-images.githubusercontent.com/22158882/85217753-12f12700-b349-11ea-9467-ad6f81437f9e.png">
