### ISSUE TITLE
Tamil: add positioning of marks on U+25CC

### ISSUE THREAD

**Issue by emuller-amazon** [googlefonts/noto-fonts#648]
Currently, there is no support to position marks with U+25CC as the base. <25CC, 0BC0> works more or less by accident, but <25CC, 0B82> has the anusvara on the right side of the dotted circle rather than on top of it.

**Comment by roozbehp** [comment]
Thanks a lot @emuller-amazon for the report. This is indeed an important issue for Android too.

**Comment by jungshik** [comment]
@JelleBosmaMT

**Comment by JelleBosmaMT** [comment]
Why would I add mark attachment for <25CC, 0BC0> if that would look exactly the same as without mark attachment?
I have it on good authority that anusvara 0B82 is not used for Tamil or anything else: www.unicode.org/L2/L2012/12018-tamil-anusvara-depr.pdf. Noto Sans Tamil has it as a spacing glyph, so that it cannot be confused with a Virama.

**Comment by nizarsq** [comment]
Look like U+25CC and U+0BC0 have been removed from NotoSansTamil and NotoSerifTamil. @marekjez86 can you double check it?

**Comment by nizarsq** [comment]
I agree with @JelleBosmaMT, they look exactly the same as without mark attachment. This issue seems to be fixed.
<img width="1226" alt="Screen Shot 2020-06-23 at 10 49 22 PM" src="https://user-images.githubusercontent.com/22158882/85505752-e127cc80-b5a3-11ea-99ab-84b26a197570.png">
