### ISSUE TITLE
U+1E9A LATIN SMALL LETTER A WITH RIGHT HALF RING

### ISSUE THREAD

**Issue by DLasher106** [googlefonts/noto-fonts#666]
U+1E9A should have the half-ring above _and to the right_ of the a. See http://www.unicode.org/versions/Unicode5.1.0/erratafixed.html.

The character decomposes to 0061 02BE, the latter being spacing, not combining.

A Unicode Mail List discussion is at http://unicode.org/mail-arch/unicode-ml/y2002-m08/0450.html.

**Comment by TidharC** [comment]
I can repro this, but it doesn't seem specific to Noto: Lucida Grande renders the same way (see screenshot).
![notosansawithrighthalfring](https://cloud.githubusercontent.com/assets/16353803/18763542/b9f3d2d6-80c2-11e6-932c-a69a051b809d.png)

**Comment by nizarsq** [comment]
1- U+1E9A  half-ring above and to the right of the a. This issue fixed
2- The character decomposes to 0061 02BE, the latter being spacing, not combining. I think this is intentional @marekjez86 any  thoughts?
<img width="459" alt="Screen Shot 2020-07-23 at 8 54 52 PM" src="https://user-images.githubusercontent.com/22158882/88359235-c3769000-cd26-11ea-84ee-73e472691eca.png">

**Comment by moyogo** [comment]
1E9A has a compatibility equivalence with 0061 02BE, not a canonical equivalence, so it's OK if they look different.

Confirmed as fixed since the right half ring is on the top right.
