### ISSUE TITLE
Dashboard with Unicode coverage by script

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#700]
What % of Unicode is covered by Noto? If we had a public dashboard, we could reply to this [Tweet](https://twitter.com/FakeUnicode/status/734858637923868673). Tweets aside, it really would be good to have some simple dashboard that shows everyone what’s there and what’s missing. If there’s already code to compute this in [nototools](https://github.com/googlei18n/nototools/tree/master/nototools), it would be good to publish the results (not just the code) on the web, and link to that from the README and/or FAQ.

**Comment by dougfelt** [comment]
Sure. What level of detail are you thinking of when you say "what's there and what's missing?"

Breaking things down by block and unicode version is easy.  Breaking things down by script could work too, but if we include things like script_extensions the scripts overlap a bit.  Since Noto was designed around Unicode 6.1 it's probably important to call out how we fare against this benchmark as well as against Unicode 9 or some other benchmark.  I'm thinking of breaking things down by script and unicode version.

**Comment by brawer** [comment]
Yes, per script and Unicode version would be great.

**Comment by dougfelt** [comment]
OK.  In general we meet our targets (Unicode 6.1 chars with the given script/script extensions) but there are edge cases where the right target isn't this simply defined.  A better target would be script/language dependent, so we end up special casing code for these scripts to define the right target, and we then also have to explain what the target is.  Some examples are Nastaliq, Cypriot, CJK, Emoji, Symbols.  

What should we do about this?  Anything?

See an example below.  This is based on Unicode 6.1, the target for a script is the set of codepoints with that script or with that script in its script extensions.  This is by Noto font, and lists the top few scripts covered by that font in order of the number of codepoints.  Percentages and ratios are given where the coverage/target ratio is 1 or more, otherwise just the number of codepoints.  This does not include codepoints whose script is inherited, and excludes some common codepoints entirely (NUL, CR, space, no-break space, BOM, and a few others).  In a few fonts listed below some codepoints contribute to multiple scripts.

```
Arabic
    Arab   1088/1262  86%
    Zyyy          24 
Nastaliq
    Arab    221/1262  17%
    Zyyy          35 
Imperial Aramaic
    Armi       31/31 100%
Armenian
    Armn       92/92 100%
Avestan
    Avst       61/61 100%
    Zyyy           2 
Balinese
    Bali     121/121 100%
Bamum
    Bamu     657/657 100%
Batak
    Batk       56/56 100%
Bengali
    Beng       94/97  96%
    Zyyy          50 
Brahmi
    Brah     108/108 100%
Buginese
    Bugi       31/31 100%
Buhid
    Buhd       22/22 100%
Canadian Aboriginal
    Cans     710/710 100%
    Zyyy           5 
    Latn           1 
Carian
    Cari       49/49 100%
Cham
    Cham       83/83 100%
    Zyyy          34 
Cherokee
    Cher       85/85 100%
Coptic
    Copt     137/137 100%
    Zyyy           1 
    Grek           1 
Cypriot
    Cprt      55/112  49%
Devanagari
    Deva     204/205  99%
    Zyyy          51 
Deseret
    Dsrt       80/80 100%
Egyptian Hieroglyphs
    Egyp   1071/1071 100%
Ethiopic
    Ethi     495/495 100%
Georgian
    Geor     122/129  94%
Glagolitic
    Glag       94/97  96%
Gothic
    Goth       27/27 100%
    Zyyy           2 
Gujarati
    Gujr       96/98  97%
    Zyyy          50 
Gurmukhi
    Guru       91/93  97%
    Zyyy          51 
Hanunoo
    Hano       23/23 100%
Simplified
    Hani 30673/76236  40%
    Hang 11739/11971  98%
    Zyyy   1234/6396  19%
    Kana     312/565  55%
Traditional
    Hani 30673/76236  40%
    Hang 11739/11971  98%
    Zyyy   1234/6396  19%
    Kana     312/565  55%
Hebrew
    Hebr     133/133 100%
    Zyyy           3 
Old Italic
    Ital       35/35 100%
Javanese
    Java       91/91 100%
Japanese
    Hani 30673/76236  40%
    Hang 11739/11971  98%
    Zyyy   1234/6396  19%
    Kana     312/565  55%
Kayah Li
    Kali       48/48 100%
Kharoshthi
    Khar       65/65 100%
Khmer
    Khmr     146/146 100%
    Zyyy          39 
Kannada
    Knda       88/98  89%
    Zyyy          50 
Korean
    Hani 30673/76236  40%
    Hang 11739/11971  98%
    Zyyy   1234/6396  19%
    Kana     312/565  55%
Kaithi
    Kthi       86/86 100%
    Zyyy          10 
(LGC)
    Latn   1034/1292  80%
    Grek     363/515  70%
    Zyyy    357/6396   5%
    Cyrl     296/419  70%
Tai Tham
    Lana     127/127 100%
    Zyyy           1 
Lao
    Laoo       67/67 100%
    Zyyy          48 
Lepcha
    Lepc       74/74 100%
Limbu
    Limb       67/67 100%
    Zyyy           1 
    Tirh        1/12   8%
    Telu        1/98   1%
Linear B
    Linb     268/268 100%
Lisu
    Lisu       48/48 100%
    Zyyy           2 
Lycian
    Lyci       29/29 100%
Lydian
    Lydi       27/27 100%
MONO
    Latn    367/1292  28%
    Cyrl     273/419  65%
    Zyyy    148/6396   2%
    Grek      75/515  14%
Mandaic
    Mand       30/30 100%
Malayalam
    Mlym     100/103  97%
    Zyyy          50 
Mongolian
    Mong     156/156 100%
    Zyyy          36 
    Yiii           2 
Meetei Mayek
    Mtei       79/79 100%
Myanmar
    Mymr     189/189 100%
N'Ko
    Nkoo       59/59 100%
    Zyyy           9 
    Arab           4 
    Thaa        3/65   4%
Ogham
    Ogam       29/29 100%
Ol Chiki
    Olck       48/48 100%
Old Turkic
    Orkh       73/73 100%
Oriya
    Orya       92/94  97%
    Zyyy          50 
Osmanya
    Osma       40/40 100%
Phags-Pa
    Phag       59/59 100%
    Zyyy          26 
    Hani          21 
    Yiii     20/1246   1%
Inscriptional Pahlavi
    Phli       27/27 100%
Phoenician
    Phnx       29/29 100%
Inscriptional Parthian
    Prti       30/30 100%
Rejang
    Rjng       37/37 100%
Runic
    Runr       78/78 100%
    Zyyy           3 
Samaritan
    Samr       61/61 100%
    Zyyy           1 
Old South Arabian
    Sarb       32/32 100%
Saurashtra
    Saur       81/81 100%
Shavian
    Shaw       48/48 100%
Sinhala
    Sinh       82/82 100%
    Zyyy          49 
Sundanese
    Sund       72/72 100%
Syloti Nagri
    Sylo       56/56 100%
    Zyyy           3 
Syriac
    Syrc       93/93 100%
    Zyyy          25 
    Arab     14/1262   1%
    Thaa       10/65  15%
Tagbanwa
    Tagb       20/20 100%
Tai Le
    Tale       45/45 100%
    Zyyy           6 
New Tai Lue
    Talu       83/83 100%
Tamil
    Taml       74/78  94%
    Zyyy          56 
Tai Viet
    Tavt       72/72 100%
    Latn           1 
Telugu
    Telu       95/98  96%
    Zyyy          50 
Tifinagh
    Tfng       59/59 100%
Tagalog
    Tglg       22/22 100%
Thaana
    Thaa       65/65 100%
    Zyyy          13 
    Arab           3 
Thai
    Thai       86/86 100%
    Zyyy           3 
Tibetan
    Tibt     207/207 100%
    Zyyy           5 
Ugaritic
    Ugar       31/31 100%
Vai
    Vaii     300/300 100%
Old Persian
    Xpeo       50/50 100%
Cuneiform
    Xsux     982/982 100%
Yi
    Yiii   1246/1246 100%
Emoji
    Zyyy    906/6396  14%
Symbols
    Zyyy   4656/6396  72%
    Brai     256/256 100%
    Grek     146/515  28%
```

**Comment by verdy-p** [comment]
coverage by codepoint only is insufficient, notably for scripts that have *required* contextual forms (including all cursive scripts like Arabic, more needed for Nastaliq, almost all Indic scripts for their conjuncts).
Counting glyphs would also be inusufficient, notably in clusters where the compound require correct positioning to make correct distincttions (notably more "dot-like" diacritics, e.g for sin vs. shin dots in Hebrew, even if baser letters usually don't have contextual forms except in cursive/handwritten/brushed styles).

**Comment by marekjez86** [comment]
would be useful...but we will not do it at this point.
