### ISSUE TITLE
U+033B COMBINING SQUARE BELOW should look like a rectangle

### ISSUE THREAD

**Issue by roozbehp** [googlefonts/noto-fonts#734]
According to the Unicode errata, dated 2016-08-23: "The glyph shown for U+033B COMBINING SQUARE BELOW is incorrect and will be updated in a future version of the standard. The images below show the current glyph as it appears in the charts (on the left) and the revised glyph (on the right)."

![](http://www.unicode.org/errata/U033B-glyphs.jpg)

See http://www.unicode.org/L2/L2016/16178-ipa-laminal.pdf for more information.

The problem exists in both Noto Sans and Noto Serif.

**Comment by jungshik** [comment]
Has a bug been filled against Robotics as well?

**Comment by roozbehp** [comment]
Roboto bug is https://github.com/google/roboto/issues/202

**Comment by nizarsq** [comment]
Bug verification in progress.

**Comment by nizarsq** [comment]
This bug is fixed for all fonts except for NotoSans-Italic
[NotoSans-Black-734.pdf](https://github.com/googlei18n/noto-fonts/files/620395/NotoSans-Black-734.pdf)
[NotoSansDisplay-Black-734.pdf](https://github.com/googlei18n/noto-fonts/files/620394/NotoSansDisplay-Black-734.pdf)
[NotoSansDisplay-Italic-734.pdf](https://github.com/googlei18n/noto-fonts/files/620393/NotoSansDisplay-Italic-734.pdf)
[NotoSans-Italic-734.pdf](https://github.com/googlei18n/noto-fonts/files/620398/NotoSans-Italic-734.pdf)
[NotoSerif-Black-734.pdf](https://github.com/googlei18n/noto-fonts/files/620396/NotoSerif-Black-734.pdf)
[NotoSerifDisplay-Black.pdf](https://github.com/googlei18n/noto-fonts/files/620397/NotoSerifDisplay-Black.pdf)
[NotoSerifDisplay-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/620401/NotoSerifDisplay-Italic.pdf)
[NotoSerif-Italic.pdf](https://github.com/googlei18n/noto-fonts/files/620400/NotoSerif-Italic.pdf)
[OldNotoSerif-Regula.pdf](https://github.com/googlei18n/noto-fonts/files/620399/OldNotoSerif-Regula.pdf)

``<html><span lang="sr"><p>&#x33b;</p></span></html>``

**Comment by marekjez86** [comment]
The original issue with U+033B COMBINING SQUARE BELOW was that square could be mis-interpreted as a circle. Hence the desire to make U+033B COMBINING SQUARE BELOW more like a rectangle. IMHO, there's no confusion NotoSans-Italic version of U+033B COMBINING SQUARE BELOW is a circle, hence this will be a lower priority to deal with (because all other U+033B COMBINING SQUARE BELOW are rectangles now)

**Comment by marekjez86** [comment]
quote from http://www.unicode.org/L2/L2016/16178-ipa-laminal.pdf "We recommend that this diacritic be made extra-large so that its shape is clearly a square, not a circle"

**Comment by nizarsq** [comment]
@marekjez86 I agree with you about the priority. However, I compared U+033B and U+0325 using NotoSans-Italic (Pink) and NotoSerif-Italic (Green) and I think NotoSans-Italic might cause confusion. Please check attached pdf. Thanks
``<html lang="en-fonipa"> <p><span style="font-weight:700">O̻O̥</span></p> </html>``
[NotoSans-Italic and NotoSerif-Italic 734.pdf](https://github.com/googlei18n/noto-fonts/files/676355/NotoSans-Italic.and.NotoSerif-Italic.734.pdf)

**Comment by marekjez86** [comment]
OK. makes sense. thanks for catching this.

**Comment by nizarsq** [comment]
U+033B looks good for current NotoSans, NotoSerrif and NotoSansMono
<img width="529" alt="Screen Shot 2020-07-21 at 9 37 35 PM" src="https://user-images.githubusercontent.com/22158882/88134783-68179700-cb9a-11ea-9ced-c31c3b223bd9.png">
