### ISSUE TITLE
Noto Serif Kannada Review

### ISSUE THREAD

**Issue by sridatta1** [googlefonts/noto-fonts#815]
I'm a native user of Kannada. A PDF of review of Noto Serif Kannada(only design issues) is attached.
Also when were Serif fonts for major Indic scripts released, according to https://github.com/googlei18n/noto-fonts/tree/master/hinted they were updated 7 months ago
These aren't reflected in https://www.google.com/get/noto/updates/
[Noto Serif Kannada Review.pdf](https://github.com/googlei18n/noto-fonts/files/673137/Noto.Serif.Kannada.Review.pdf)

**Comment by marekjez86** [comment]
@sridatta1 : Thank you for a very thorough feedback and suggestions on the design. We are planning to re-release them and, I think, the font designer(s) will take them into consideration. You are right, we have re-released Indic serif fonts a while ago on github, but they aren't updated on get/noto. We control the github releases, can update releases on github at any time, but we need to coordinate releases to other locations/sites or components with the owners of these sites/components. Hence the discrepancy. I'll keep this bug open because the feedback will be useful in the future work. Thanks again.

**Comment by roozbehp** [comment]
Thanks a lot @sridatta1. Are you the same Sridatta who co-authored http://www.unicode.org/L2/L2016/16031-kannada-siddham.pdf and other Unicode proposals?

**Comment by sridatta1** [comment]
@roozbehp yes.
The feedback on digits may also be applicable to Telugu, but I have to verify from printed books.
The are also some common issues across Indic scripts which I will report seperately

**Comment by JelleBosmaMT** [comment]
In the case of Noto Sans Kannada, the usage of large numerals is an
intentional feature. It goes back to the original design proposal, which
has been agreed to by various reviewers before the design was started and
approved afterwards. For a design that is intended to be used in the UI of
mobile devices where font sizes and application layouts have been designed
for Latin fonts, having numerals that align with the Kannada head-stroke
will render them less than clear. Wether doing the same for the Serif
fonts, is a different matter.

**Comment by davelab6** [comment]
It seems by this logic the numeral size of the serif fonts should by
default not be the same, since they will not be used in UI text?

**Comment by JelleBosmaMT** [comment]
It is not necessarily a binary logic.

 Whilst not UI fonts, the Noto Serif fonts are not exactly aiming to be
fonts just for static print publications either. There is a whole world of
usages in between. And we are going to have a range of weights that
includes the very heavy and the very condensed. If you work from a
convention that did not have to accommodate this, then maybe you have to
try the unconventional here and there.

**Comment by davelab6** [comment]
I'm sorry I don't follow you. Very heavy weights tend to only be used at
larger sizes; while the deviation from norm in the sans was made for
atypically small sizes.

**Comment by sridatta1** [comment]
also ರ್ರ should be like Noto Sans Kannada, it is written with ra-ottu instead of repha (see #5 )

**Comment by sridatta1** [comment]
I'm closing this issue as I see they being fixed in the latest fonts. I'll file new issues for any design issue in the above document.

**Comment by kidasund** [comment]
I have a problem with kShNa using Noto Serif Kannada.
I get 
![image](https://user-images.githubusercontent.com/77251997/104139037-3f64a300-536e-11eb-90af-cceefcb6dd7e.png)
I use xelatex. 
Thank you
