### ISSUE TITLE
Android Tofu for Monospace IPA

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-fonts#824]
On an Android 7.1.1 device (Google Nexus 5X), [this test page](https://github.com/googlei18n/noto-source/blob/master/test/LGC/und-fonipa.html) has lots of Tofu:

![image](https://cloud.githubusercontent.com/assets/1527880/21933048/fa67f7f4-d9a3-11e6-9cd1-6e461bbf1413.png)

Compare to how the same page gets rendered on macOS:

![image](https://cloud.githubusercontent.com/assets/1527880/21933132/753e7b6a-d9a4-11e6-9684-282be50b347d.png)

**Comment by jungshik** [comment]
@brawer   can you file a Chrome bug at https://crbug.com and let me know the bug number? 
There are at least two fonts on Nexus 5x that can render(most of, if not all) the above much better (Roboto and Noto Serif). Chrome should pick up either of them instead of mixing multiple fonts. 

BTW, 'this test page' link in your report does not work for me. noto-source repo does not have test/und-fonipa, either.

**Comment by marekjez86** [comment]
@jungshik @brawer : my bad, I reorganized the tests -- the new location is https://github.com/googlei18n/noto-source/blob/master/test/LGC/und-fonipa.html

(I updated the comment above)

**Comment by brawer** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=692735

**Comment by eaenet** [comment]
The page in question explicitly sets the font-family to the following
"SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;

Thus we're required to try all of those fonts, in order, before falling back on a suitable system font with better coverage. We can't just ignore the author specified font and pick a font we think is better.

We should, however, find a suitable font for the missing glyphs instead of rendering them as missing. Mixing fonts though is unavoidable with the font-family as specified.

**Comment by marekjez86** [comment]
the issue still persists, but this is NOT a Noto issue
