### ISSUE TITLE
Hebrew cantillation marks in both Sans and Serif Hebrew have problems

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#844]
Hebrew cantillation marks in both Sans and Serif Hebrew according to the information I was given have problems: the marks should appear above/below the letter, but in the attached samples they are rendered to the right of the letter (note that Hebrew fonts generated by both pipeline and Glyphs.app from the same sources have this problem). The following Glyphs.app generated fonts can serve as a sample. [NotoHebrew.zip](https://github.com/googlei18n/noto-fonts/files/781035/NotoHebrew.zip)

[specimen-Hebrew-combining-marks-Hebrew-Serif-GRegularAndPRegular.pdf](https://github.com/googlei18n/noto-fonts/files/781023/specimen-Hebrew-combining-marks-Hebrew-Serif-GRegularAndPRegular.pdf)
[specimen-Hebrew-combining-marks-Hebrew-Sans-GRegularAndPRegular.pdf](https://github.com/googlei18n/noto-fonts/files/781022/specimen-Hebrew-combining-marks-Hebrew-Sans-GRegularAndPRegular.pdf)

**Comment by kmansourMT** [comment]
Please verify your test files first. I think the test sequences consist of "mark + base" instead of "base + mark". For instance, one should test the sequence of Alef (05D0) followed by Qamats (05B8), and not the reverse. The logical sequence of base plus mark should always be observed even when the writing is moving right to left. Following is the rendering of 05D0 + 05B8 which looks right to me:
![screen shot 2017-02-16 at 14 31 09](https://cloud.githubusercontent.com/assets/12738181/23044341/a192536a-f454-11e6-8d5e-fea2131546a7.png)

**Comment by marekjez86** [comment]
@kmansourMT : Thank you for pointing this out.

**Comment by marekjez86** [comment]
I need to investigate more.

**Comment by nizarsq** [comment]
> I need to investigate more.

@marekjez86  do you have test files?

**Comment by kosmynkab** [comment]
I verified the files - this issue was caused by the software used to set the test document originally, not the font itself. Issue can be closed.
