### ISSUE TITLE
Noto Sans: Ṳ ṳ should have dieresis below, not above

### ISSUE THREAD

**Issue by moyogo** [googlefonts/noto-fonts#920]
In Noto Sans (from noto-fonts-alpha), Ṳ, ṳ (1E72, 1E73) use dieresis as a component but should use dieresisbelowcomb instead.

**Comment by TidharC** [comment]
I checked:
1E72 1E73
Ṳ   ṳ

in Noto Sans Regular and Noto Serif Regular.  Sans shows the dieresis above, which is wrong; Noto Serif (and fonts other than Noto) has the dieresis below, as expected.

![notoudieresisbelow](https://user-images.githubusercontent.com/16353803/27048162-a19b04b8-4f5f-11e7-8cc3-88ae14ef57c8.png)



Font location:
https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/
Font versions:
Noto Sans Regular 1.902
Noto Serif Regular 1.903

Note that Noto Sans Bold and Noto Sans variable font also show the dieresis above.

@moyogo, do you see the same results?

**Comment by moyogo** [comment]
@TidharC Yes.

**Comment by nizarsq** [comment]
This issue fixed in the current [NotoSans]( https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans)
<img width="731" alt="Screen Shot 2020-07-17 at 10 29 10 PM" src="https://user-images.githubusercontent.com/22158882/87845514-f0392c00-c87c-11ea-945b-159dab278026.png">
