### ISSUE TITLE
Incorrect handling of  '`' in NotoSans-Italic and NotoSansDisplay-Italic 

### ISSUE THREAD

**Issue by JoeyLi-1** [googlefonts/noto-fonts#970]
Hi There,

This is not a defect report, just want to ask a question which I could not find answer in google. Thank you!

Could someone help me that why the character combined with the following character? Like I`m , it will display like 
![image](https://user-images.githubusercontent.com/20162464/30845400-c99570ac-a2c5-11e7-9f1b-c751c92eecf7.png)

I m using the font like this:
`<link href="https://fonts.googleapis.com/css?family=Noto+Sans:400,400i,700,700i" rel="stylesheet" type="text/css">`

@dougfelt @roozbehp @marekjez86  @xiangyexiao 

Thanks,
Joey

**Comment by marekjez86** [comment]
The character that you are using above is called "grave accent" -- see https://en.wikipedia.org/wiki/Grave_accent . The behaviour that you describe is correct for this character.

I think you want to use apostrophe character : see https://en.wikipedia.org/wiki/Apostrophe

**Comment by dougfelt** [comment]
This is a spacing character, not a combining mark.  It shouldn't overlap the following character.

**Comment by marekjez86** [comment]
@dougfelt : thank you. I stand corrected.

**Comment by marekjez86** [comment]
@JoeyLi-1 : I ran tests with the most recent fonts that you can obtain from https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf (note these fonts will soon appear in get/noto )

The bug that you reported for NotoSans is not reproducible there (i.e., it's fixed). However it is not fixed in NotoSans-Italic (see the image below) nor NotoSansDisplay-Italic (same behavior).
![notosans-italic-grave](https://user-images.githubusercontent.com/13322623/30877871-eeae2de0-a2af-11e7-9a0f-58c245ac3bc7.jpeg)


Here the pdf files with the test results against various Noto LGC fonts:

[en-970-LGC-Sans-Italic-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1334513/en-970-LGC-Sans-Italic-vs-self.pdf)
[en-970-LGC-Sans-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1334509/en-970-LGC-Sans-Regular-vs-self.pdf)
[en-970-LGC-SansDisplay-Italic-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1334508/en-970-LGC-SansDisplay-Italic-vs-self.pdf)
[en-970-LGC-SansDisplay-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1334506/en-970-LGC-SansDisplay-Regular-vs-self.pdf)
[en-970-LGC-SansMono-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1334505/en-970-LGC-SansMono-Regular-vs-self.pdf)
[en-970-LGC-Serif-Italic-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1334507/en-970-LGC-Serif-Italic-vs-self.pdf)
[en-970-LGC-Serif-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1334511/en-970-LGC-Serif-Regular-vs-self.pdf)
[en-970-LGC-SerifDisplay-Italic-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1334510/en-970-LGC-SerifDisplay-Italic-vs-self.pdf)
[en-970-LGC-SerifDisplay-Regular-vs-self.pdf](https://github.com/googlei18n/noto-fonts/files/1334512/en-970-LGC-SerifDisplay-Regular-vs-self.pdf)

**Comment by JoeyLi-1** [comment]
@dougfelt  @marekjez86 
Thank you both! Reply so fast, amazing! Your answer solved my question, close this issue.

**Comment by nizarsq** [comment]
Look like this issue has been resolved. Tested U+0060 using NotoSans,NotoSerif and NotoSansMono and it looks ok in the current versions in 
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSansMono
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans
https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSerif


<img width="555" alt="Screen Shot 2020-07-17 at 10 05 18 PM" src="https://user-images.githubusercontent.com/22158882/87845137-9aaf5000-c879-11ea-8801-740ae7aefcd9.png">
