### ISSUE TITLE
Phase II Bengali TTF fonts need U+02BC 'MODIFIER LETTER APOSTROPHE'

### ISSUE THREAD

**Issue by marekjez86** [googlefonts/noto-fonts#986]
Phase II Bengali TTF fonts need U+02BC 'MODIFIER LETTER APOSTROPHE' (it's already in SOW15).

Alternatively: we need to ship Phase III Bengali

**Comment by jungshik** [comment]
Just because Noto Sans Bengali does not have U+02BC does NOT mean that we have an issue here. 
As long as there's no "opentype interaction" between Bengali characters and U+02BC and U+02BC is covered by another font on Android, we don't need U+02BC in Bengali fonts. 

Not having U+02BC in Bengali fonts may makes 'kern' off slightly, but wouldn't be that bad.

**Comment by nizarsq** [comment]
U+02BC exist in the current NotoSansBengali.ttf (hinted and unhinted). @marekjez86 should 
 we close this bug?
<img width="1177" alt="Screen Shot 2020-06-11 at 7 23 38 AM" src="https://user-images.githubusercontent.com/22158882/84398261-988c0e80-abb4-11ea-9dbf-5b8f1f83ab26.png">
