### ISSUE TITLE
[Firefox on Ubuntu] Old Style Numerics of Noto Sans & Noto Serif do not render correctly for normal stretch, weights 400 and 700

### ISSUE THREAD

**Issue by ytx21cn** [googlefonts/noto-fonts#996]
**OS version: Ubuntu 17.10
Firefox version: 56.0
Chromium version:  62.0.3202.75**

When using Firefox and having specified in the CSS to use old-style numerics, the old-style numerics for normal stretch, weights 400 (regular) and 700 (bold), are not rendered.
This problem does not happen in Chromium.

Testing pages (please open the .html pages inside): 
[Noto test.zip](https://github.com/googlei18n/noto-fonts/files/1444590/Noto.test.zip)

## Noto Sans
Opening the page with **Firefox** gets the following. Notice that the weight numbers on the left and the "1234567890" strings in **regular** and **bold** weights are rendered as lining numerics, although I have specified in CSS to use old-style numerics.
![noto sans old-style num in firefox](https://user-images.githubusercontent.com/5900105/32420616-d4cfd598-c241-11e7-9ca5-a414ca22c341.png)

However, when opening the same page with **Chromium**, there is no such problem.
![noto sans old-style num in chromium](https://user-images.githubusercontent.com/5900105/32420632-12a57eb8-c242-11e7-9f8d-4bd91be1d343.png)

## Noto Serif

Similar problems are observed.

Opening in **Firefox**:
![noto serif old-style num in firefox](https://user-images.githubusercontent.com/5900105/32420732-db7e980a-c243-11e7-8cc9-5be2083e20aa.png)

Opening in **Chromium**:
![noto serif old-style num in chromium](https://user-images.githubusercontent.com/5900105/32420738-ee999886-c243-11e7-9340-3a6267749bc4.png)

**Comment by brawer** [comment]
If it works in Chrome, this sounds more like a problem with Firefox, not with the fonts. Would you mind reporting this to Firefox? Thanks in advance. Also thanks for posting the bugzilla ID here, for later reference.

**Comment by anthrotype** [comment]
could it be the opentype sanitizer maybe?
I believe Firefox uses it to validate the OT layout tables
https://github.com/khaledhosny/ots/

**Comment by ytx21cn** [comment]
I have also tested another font that has old-style figures, Raleway, and there is no such problem.

**Comment by ytx21cn** [comment]
Also filed the bug on Firefox Bugzilla.
[](https://bugzilla.mozilla.org/show_bug.cgi?id=1414948)

**Comment by ytx21cn** [comment]
Found this issue both in Firefox 56 and Firefox 57

**Comment by mewtant** [comment]
This problem is not peculiar to Firefox.  If I compile the following with either luatex or xetex in an up-to-date installation of TeX Live, the output shows lining figures.

    \documentclass{article}
    \usepackage{fontspec}
    \defaultfontfeatures{Numbers=OldStyle}
    \setmainfont{Noto Serif}
    \setsansfont{Noto Sans}
    \begin{document}
    1234567890

    \sffamily
    1234567890
    \end{document}

However, with Noto Sans Light or Noto Sans Display, the output shows lowercase figures as expected.

**Comment by jake-low** [comment]
I was seeing the same problem that @ytx21cn was reporting, so I attempted to reproduce the issue.

OS version: MacOS High Sierra (10.13.3)
Chrome version:  65.0.3325.162
Firefox version: 59.0
Safari version: 11.0.3

Repro steps:

1. Download "Noto Sans" and "Noto Serif" from [google.com/get/noto](https://www.google.com/get/noto/) and install all of the TTF files in each archive.
2. Download @ytx21cn's [Noto test.zip](https://github.com/googlei18n/noto-fonts/files/1444590/Noto.test.zip) and extract it.
3. Open `Noto.test/Noto Sans.html` and `Noto.test/Noto Serif.html` in a bunch of browsers.

Shown below:
Left to right: Chrome 65, Firefox 59, Safari 11
Top: Noto Sans, bottom: Noto Serif

<img width="1680" alt="Chrome, Firefox and Safari displaying sample text in Noto Sans and Noto Serif, in a variety of font weight and font style combinations. A CSS rule (not shown) sets the text to display using old-style numerals, but in spite of this, certain combinations of font weight and font style in new-style numerals being rendered instead." src="https://user-images.githubusercontent.com/5893857/37542368-3300e338-291b-11e8-9ad6-092b8792719a.png">

Expected result:
Since `font-variant-numeric: oldstyle-nums;` is set on the `body` element, all displayed numbers should use old-style numerals.

Actual result:
Certain combinations of `font-weight` and roman/italic result in new-style(?) numerals being displayed. I've underlined all of the new-style numerals in red.

Summary:
All three browsers fail to display `oldstyle-nums` if the font weight is 400 or 700, regardless of font style (i.e. roman or italic). Chrome and Firefox also fail to display `oldstyle-nums` if the font-weight is 500 _and_ the font style is italic.

As a sanity check, I switched the font in @ytx21cn's test pages to Raleway (which I downloaded and installed every variant of from fonts.google.com) and none of the tested browsers had any trouble displaying old-style numerals in that typeface, under any combination of weight and style.

<img width="1680" alt="Chrome, Firefox and Safari correctly rendering old-style numerals in the Raleway typeface, in a variety of font weight and font style combinations." src="https://user-images.githubusercontent.com/5893857/37543733-c9bfb246-291f-11e8-902c-b6c607c831f5.png">

Conclusion:

I believe this is an issue with the Noto fonts, and not with a particular browser or operating system. If I can provide more information to help track down this bug, let me know.

P.S. To all the maintainers: thanks for creating Noto and sharing it with the world!

**Comment by mewtant** [comment]
Now that TeX Live 2018 is out, my minimal example of January 15th no longer shows a problem.

**Comment by jake-low** [comment]
I happened to notice this week that this issue is fixed for me. I thought I'd take a minute to follow up briefly on my previous comment.

OS version: MacOS Catalina (10.15.2)
Chrome version: 80.0.3987.116
Firefox version: 72.0.1
Safari version: 13.0.4

I used exactly the same repro steps that I described [above](https://github.com/googlefonts/noto-fonts/issues/996#issuecomment-373841838): downloading the latest "Noto Sans" and "Noto Serif" zip archives from google.com/get/noto and installing all the fonts (by putting them in ~/Library/Fonts). Then I downloaded @ytx21cn's Noto test.zip and opened the files in it in all three browsers.

Shown below:
Left to right: Chrome 80, Firefox 72, Safari 13
Top: Noto Sans, bottom: Noto Serif

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/5893857/75086674-bb9e8f80-54eb-11ea-9c36-9b104b9c41ee.png">

Summary:
Chrome and Firefox are both displaying the oldstyle numerals correctly, for both Noto Sans and Noto Serif, in all combinations of weight and style. Safari is displaying the default `sans-serif` and `serif` fonts (Helvetica and Times, I think) because apparently Safari 12 [broke or disabled support for local fonts](https://www.reddit.com/r/MacOS/comments/9jp5m3/psa_safari_12_disablednerfed_setting_custom_fonts/). I tried adding a `@font-face` rule to the CSS in the test pages that specified `src: local("Noto Sans")` but that change had no effect.

I then decided to try _uninstalling_ the local Noto fonts and adding Google Fonts stylesheets to the test pages. I added this line to `Noto Sans.html`

```
<link href="https://fonts.googleapis.com/css?family=Noto+Sans:400,400i,700,700i&display=swap" rel="stylesheet">
```

... and this line to `Noto Serif.html`:
```
<link href="https://fonts.googleapis.com/css?family=Noto+Serif:400,400i,700,700i&display=swap" rel="stylesheet">
```

And refreshed the page in all browsers. This is what I saw:

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/5893857/75086965-39b06580-54ef-11ea-9d73-41ec06db7d28.png">

Summary:
Unlike the screenshot above, all lines are being displayed in either the 400-weight or 700-weight variant, because those are the only weights available from Google Fonts.

Both Chrome and Safari are failing to display oldstyle numerals in any configuration. Firefox shows them correctly in all configurations.

**Takeaway for anyone encountering this or a similar issue:**
At the time of writing, the font files available at google.com/get/noto seem to work correctly when displaying oldstyle numerals. However, the files served by the Google Fonts API exhibit issues, some of which vary by browser.

**Comment by nizarsq** [comment]
@jake-low did you try to test this issue with the latest Noto Sans build, you can get it from this directory https://github.com/googlefonts/noto-fonts/tree/master/phaseIII_only/hinted/ttf/NotoSans

**Comment by ytx21cn** [comment]
Problems no longer exist with **version 2.00**.
![Noto Sans](https://user-images.githubusercontent.com/5900105/87750931-a6cfda80-c7b1-11ea-946a-d90d943bba96.png)
![Noto Serif](https://user-images.githubusercontent.com/5900105/87750930-a59ead80-c7b1-11ea-969c-90727228c090.png)

**Comment by nizarsq** [comment]
@ytx21cn great thanks
